let bai_tap_theo_lop = [
     //Class Odne
     { class: 1, ex: '2 + 3 =', kq: 5 },
     { class: 1, ex: '1 + 3 =', kq: 4 },
     { class: 1, ex: '2 + 6 =', kq: 8 },
     { class: 1, ex: '1 + 4 =', kq: 5 },
     { class: 1, ex: '2 + 8 =', kq: 10 },
     { class: 1, ex: '3 + 6 =', kq: 9 },
     { class: 1, ex: '3 + 7 =', kq: 10 },
     { class: 1, ex: '3 + 2 =', kq: 5 },
     { class: 1, ex: '4 + 5 =', kq: 9 },
     { class: 1, ex: '4 + 2 =', kq: 6 },
     { class: 1, ex: '4 + 1 =', kq: 5 },
     { class: 1, ex: '5 + 1 =', kq: 6 },
     { class: 1, ex: '5 + 2 =', kq: 7 },
     { class: 1, ex: '5 + 4 =', kq: 9 },
     { class: 1, ex: '6 + 2 =', kq: 8 },
     { class: 1, ex: '6 + 3 =', kq: 9 },
     { class: 1, ex: '6 + 4 =', kq: 10 },
     { class: 1, ex: '7 + 1 =', kq: 8 },
     { class: 1, ex: '7 + 3 =', kq: 10 },
     { class: 1, ex: '7 + 2 =', kq: 9 },
     { class: 1, ex: '8 + 1 =', kq: 9 },
     { class: 1, ex: '8 + 2 =', kq: 10 },
     { class: 1, ex: '8 + 0 =', kq: 8 },
     { class: 1, ex: '9 + 0 =', kq: 9 },
     { class: 1, ex: '9 + 1 =', kq: 10 },
     { class: 1, ex: '9 + 2 =', kq: 11 },
     { class: 1, ex: '10 + 2=', kq: 12 },
     { class: 1, ex: '10 + 0 =', kq: 10 },
     { class: 1, ex: '10 + 6 =', kq: 16 },
     { class: 1, ex: '11 + 2 =', kq: 13 },
     { class: 1, ex: '11 + 3 =', kq: 14 },
     { class: 1, ex: '11 + 6 =', kq: 17 },
     { class: 1, ex: '6 - 2 =', kq: 4 },
     { class: 1, ex: '4 - 1 =', kq: 3 },
     { class: 1, ex: '5 - 3 =', kq: 2 },
     { class: 1, ex: '3 - 1 =', kq: 2 },
     { class: 1, ex: '2 - 1 =', kq: 1 },
     { class: 1, ex: '5 - 3=', kq: 2 },
     { class: 1, ex: '4 - 2 =', kq: 2 },
     { class: 1, ex: '4 - 3 =', kq: 1 },
     { class: 1, ex: '6 - 3 =', kq: 3 },
     { class: 1, ex: '5 - 2 =', kq: 3 },
     { class: 1, ex: '5 - 0 =', kq: 5 },
     { class: 1, ex: '7 - 3 =', kq: 4 },
     { class: 1, ex: '8 - 5 =', kq: 3 },
     { class: 1, ex: '9 - 4 =', kq: 5 },
     { class: 1, ex: '7 - 6 =', kq: 1 },
     { class: 1, ex: '10 - 6 =', kq: 4 },
     { class: 1, ex: '8 - 6 =', kq: 2 },
     { class: 1, ex: '6 - 5 =', kq: 1 },
     { class: 1, ex: '4 - 3 =', kq: 1 },
     { class: 1, ex: '7 - 3 =', kq: 4 },
     { class: 1, ex: '9 - 7 =', kq: 2 },
     { class: 1, ex: '3 - 3 =', kq: 0 },
     { class: 1, ex: '8 - 4 =', kq: 4 },
     { class: 1, ex: '9 - 3 =', kq: 6 },
     { class: 1, ex: '5 - 1 =', kq: 4 },
     { class: 1, ex: '7 - 6 =', kq: 1 },
     { class: 1, ex: '8 - 8 =', kq: 0 },
     { class: 1, ex: '2 - 2 =', kq: 0 },
     { class: 1, ex: '9 - 5 =', kq: 4 },
     { class: 1, ex: '8 - 0 =', kq: 8 },
     { class: 1, ex: '3 - 1 =', kq: 2 },
     { class: 1, ex: '7 - 7=', kq: 0 },
     { class: 1, ex: '5 - 3 =', kq: 2 },
     { class: 1, ex: '6 - 2 =', kq: 4 },
     { class: 1, ex: '1 + 5 =', kq: 6 },
     { class: 1, ex: '7 - 7=', kq: 0 },
     { class: 1, ex: '5 + 2 =', kq: 7 },
     { class: 1, ex: '7 - 6 =', kq: 1 },
     { class: 1, ex: '4 + 3 =', kq: 7 },
     { class: 1, ex: '9 - 5 =', kq: 4 },
     { class: 1, ex: '7 + 1 =', kq: 8 },
     { class: 1, ex: '7 + 3 =', kq: 10 },
     { class: 1, ex: '2 + 0 =', kq: 2 },
     { class: 1, ex: '3 + 5 =', kq: 8 },
     { class: 1, ex: '5 - 2 =', kq: 3 },
     { class: 1, ex: '6 - 5 =', kq: 1 },
     { class: 1, ex: '8 - 6 =', kq: 2 },
     { class: 1, ex: '6 - 4 =', kq: 2 },
     { class: 1, ex: '7 - 3 =', kq: 4 },
     { class: 1, ex: '10 + 0 =', kq: 10 },
     { class: 1, ex: '5 +4 =', kq: 9 },
     { class: 1, ex: '8 - 2 =', kq: 6 },
     { class: 1, ex: '2 - 1 =', kq: 1 },
     { class: 1, ex: '6 + 3 =', kq: 9 },
     { class: 1, ex: '5 + 2 =', kq: 7 },
     { class: 1, ex: '9 - 4 =', kq: 5 },
     { class: 1, ex: '6 + 4 =', kq: 10 },
     { class: 1, ex: '4 + 2 =', kq: 6 },
     { class: 1, ex: '6 + 1=', kq: 7 },
     { class: 1, ex: '8 + 2 =', kq: 10 },
     { class: 1, ex: '4 - 4 =', kq: 0 },
     { class: 1, ex: '7 - 3 =', kq: 4 },
     { class: 1, ex: '3 + 6 =', kq: 9 },
     { class: 1, ex: '7 + 2 =', kq: 9 },
     { class: 1, ex: '9 - 5 =', kq: 4 },
     { class: 1, ex: '3 + 6 =', kq: 9 },
     { class: 1, ex: 'Tìm số bé nhất trong các số sau :8, 4, 10, 12 , 9', kq: 4 },
     { class: 1, ex: 'Tìm số bé nhất trong các số sau :11, 18, 19, 8', kq: 8 },
     { class: 1, ex: 'Tìm số bé nhất trong các số sau :16, 13, 14, 20', kq: 13 },
     { class: 1, ex: 'Tìm số bé nhất trong các số sau :6, 9, 10, 1, 8', kq: 1 },
     { class: 1, ex: 'Tìm số bé nhất trong các số sau :12, 11, 10, 15', kq: 10 },
     { class: 1, ex: 'Tìm số bé nhất trong các số sau :3, 6, 9, 8, 12', kq: 3 },
     { class: 1, ex: 'Tìm số bé nhất trong các số sau :12, 11, 10, 15', kq: 10 },
     { class: 1, ex: 'Tìm số bé nhất trong các số sau :8, 4, 10, 12, 9', kq: 4 },
     { class: 1, ex: 'Tìm số bé nhất trong các số sau :3, 6, 9, 8, 12', kq: 3 },
     { class: 1, ex: 'Tìm số bé nhất trong các số sau :6, 9, 10, 1, 8', kq: 1 },
     { class: 1, ex: 'Tìm số bé nhất trong các số sau :16, 13, 14, 20', kq: 13 },
     { class: 1, ex: 'Tìm số bé nhất trong các số sau :11, 18, 19, 8', kq: 8 },
     { class: 1, ex: 'Tìm số lớn nhất trong các số sau :8, 4, 10, 12 , 9', kq: 12 },
     { class: 1, ex: 'Tìm số lớn nhất trong các số sau :11, 18, 19, 8', kq: 19 },
     { class: 1, ex: 'Tìm số lớn nhất trong các số sau :16, 13, 14, 20', kq: 20 },
     { class: 1, ex: 'Tìm số lớn nhất trong các số sau :6, 9, 10, 1, 8', kq: 10 },
     { class: 1, ex: 'Tìm số lớn nhất trong các số sau :12, 11, 10, 15', kq: 15 },
     { class: 1, ex: 'Tìm số lớn nhất trong các số sau :3, 6, 9, 8, 12', kq: 12 },
     { class: 1, ex: 'Tìm số lớn nhất trong các số sau :12, 11, 10, 15', kq: 15 },
     { class: 1, ex: 'Tìm số lớn nhất trong các số sau :8, 4, 10, 12, 9', kq: 12 },
     { class: 1, ex: 'Tìm số lớn nhất trong các số sau :3, 6, 9, 8, 12', kq: 12 },
     { class: 1, ex: 'Tìm số lớn nhất trong các số sau :6, 9, 10, 1, 8', kq: 10 },
     { class: 1, ex: 'Tìm số lớn nhất trong các số sau :16, 13, 14, 20', kq: 20 },
     { class: 1, ex: 'Tìm số lớn nhất trong các số sau :11, 18, 19, 8', kq: 19 },
     { class: 1, ex: '12 + 3 ', kq: 15 },
     { class: 1, ex: '15 + 4 ', kq: 19 },
     { class: 1, ex: '16 + 2', kq: 18 },
     { class: 1, ex: '15 + 2', kq: 17 },
     { class: 1, ex: '12 + 6', kq: 18 },
     { class: 1, ex: '11 + 6', kq: 17 },
     { class: 1, ex: '11 + 4', kq: 15 },
     { class: 1, ex: '14 + 2', kq: 16 },
     { class: 1, ex: '11 + 6', kq: 17 },
     { class: 1, ex: '12 + 5', kq: 17 },
     { class: 1, ex: '11 + 8', kq: 19 },
     { class: 1, ex: '14 + 3', kq: 17 },
     { class: 1, ex: '10 + 5 ', kq: 15 },
     { class: 1, ex: '13 + 6', kq: 19 },
     { class: 1, ex: '15 + 3', kq: 18 },
     { class: 1, ex: 'Hồng có 8 que tính, Lan có 2 que tính. Hỏi cả hai bạn có bao nhiêu que tính?', kq: 10 },
     { class: 1, ex: 'Cành trên có 10 con chim, cành dưới có 5 con chim. Hỏi có tất cả bao nhiêu con chim?', kq: 15 },
     { class: 1, ex: 'Lớp 1B có 33 bạn, lớp 1C có 30 bạn. Hỏi cả hai lớp có tất cả bao nhiêu bạn?', kq: 63 },
     { class: 1, ex: 'Tháng trước Hà được 15 điểm 10, tháng này Hà được 11 điểm 10. Hỏi cả hai tháng Hà được tất cả bao nhiêu điểm 10?', kq: 26 },
     { class: 1, ex: 'Hoa có 16 cái kẹo, Hà cho Hoa thêm 3 cái kẹo nữa. Hỏi Hoa có tất cả bao nhiêu cái kẹo?', kq: 19 },
     { class: 1, ex: 'Tú có 1 chục quyển vở, Tú được thưởng 5 quyển vở nữa. Hỏi tú có tất cả bao nhiêu quyển vở?', kq: 15 },
     { class: 1, ex: 'Huệ có 2 chục bút chì, mẹ mua thêm cho Huệ 5 bút chì nữa. Hỏi Huệ có tất cả bao nhiêu bút chì?', kq: 25 },
     { class: 1, ex: 'Tổ Một làm được 20 lá cờ, tổ Hai làm được 1 chục lá cờ. Hỏi cả hai tổ làm được tất cả bao nhiêu lá cờ?', kq: 30 },
     { class: 1, ex: 'Hồng có 16 que tính, Hồng được bạn cho thêm 2 que tính. Hỏi Hồng có bao nhiêu que tính?', kq: 18 },
     { class: 1, ex: 'Trong vườn nhà Nam trồng 20 cây bưởi và 2 chục cây cam. Hỏi trong vườn nhà Nam trồng được tất cả bao nhiêu cây?', kq: 40 },
     { class: 1, ex: 'Số bé nhất trong các số sau là: 23, 31, 70, 18, 69', kq: 18 },
     { class: 1, ex: 'Số liền trước của 54 là số nào?', kq: 53 },
     { class: 1, ex: '60cm + 20cm = ....cm', kq: 80 },
     { class: 1, ex: 'Đặt tính rồi tính: 20 + 40', kq: 60 },
     { class: 1, ex: 'Đặt tính rồi tính: 87 – 59', kq: 28 },
     { class: 1, ex: 'Đặt tính rồi tính: 76 + 38', kq: 114 },
     { class: 1, ex: 'Đặt tính rồi tính: 90 – 61  ', kq: 29 },
     { class: 1, ex: 'Đặt tính rồi tính: 81 - 38', kq: 43 },
     { class: 1, ex: 'Đặt tính rồi tính: 29 + 83', kq: 112 },
     { class: 1, ex: 'Đặt tính rồi tính: 85 – 67', kq: 18 },
     { class: 1, ex: 'Đặt tính rồi tính: 46 + 58', kq: 104 },
     { class: 1, ex: 'Đặt tính rồi tính: 67 – 29', kq: 38 },
     { class: 1, ex: 'Đặt tính rồi tính: 78 + 56', kq: 134 },
     { class: 1, ex: 'Đặt tính rồi tính: 76 + 38', kq: 114 },
     { class: 1, ex: 'Đặt tính rồi tính: 95 – 31', kq: 64 },
     { class: 1, ex: 'Đặt tính rồi tính: 98 – 41', kq: 57 },
     { class: 1, ex: 'Đặt tính rồi tính: 91 – 61', kq: 30 },
     { class: 1, ex: 'Tính nhẩm :17 – 4 + 3 = ....... ', kq: 16 },
     { class: 1, ex: 'Tính nhẩm :6 + 10 + 2 =...... ', kq: 18 },
     { class: 1, ex: 'Tính nhẩm :13 – 3 + 8 = ....', kq: 18 },
     { class: 1, ex: 'Tính nhẩm :4 + 13 – 2 =........ ', kq: 15 },
     { class: 1, ex: 'Tính nhẩm :25 + 40 – 13 = ...... ', kq: 52 },
     { class: 1, ex: 'Tính nhẩm :58 – 23 + 34 =...... ', kq: 69 },
     { class: 1, ex: 'Tính nhẩm :4cm + 15cm – 6cm = ....... ', kq: 13 },
     { class: 1, ex: 'Tính nhẩm :18cm – 5cm + 6cm =........ ', kq: 19 },
     { class: 1, ex: 'Tính nhẩm :12cm + 7cm – 5cm = ....... ', kq: 14 },
     { class: 1, ex: 'Tính nhẩm :40cm – 20cm + 60cm =...... ', kq: 80 },
     { class: 1, ex: 'Tính nhẩm :17cm + 31cm – 0cm = ....... ', kq: 48 },
     { class: 1, ex: 'Tính nhẩm :30cm + 8cm – 22cm =........ ', kq: 16 },
     { class: 1, ex: 'Tính nhẩm :35cm + 7cm – 2cm =........ ', kq: 40 },
     { class: 1, ex: 'Tính nhẩm :36cm + 11cm – 12cm =........ ', kq: 35 },
     { class: 1, ex: 'Tính nhẩm :37cm + 12cm – 32cm =........ ', kq: 17 },
     { class: 1, ex: 'Tính nhẩm :38cm + 8cm – 12cm =........ ', kq: 34 },
     { class: 1, ex: 'Tính nhẩm :33cm + 19cm – 19cm =........ ', kq: 33 },
     { class: 1, ex: 'Tính nhẩm :32cm + 11cm – 17cm =........ ', kq: 26 },
     { class: 1, ex: 'Trên bờ có 20 con vịt, dưới ao có 3 chục con vịt. Hỏi có tất cả bao nhiêu con vịt?', kq: 50 },
     { class: 1, ex: 'Hoa gấp được 40 ngôi sao, chị cho Hoa thêm 50 ngôi sao nữa. Hỏi Hoa có tất cả bao nhiêu ngôi sao?', kq: 90 },
     { class: 1, ex: ' Thu gấp được 57 máy bay, Thu tặng bạn 34 máy bay. Hỏi Thu còn lại bao nhiêu máy bay?', kq: 91 },
     { class: 1, ex: 'Đoạn thẳng AB dài 10 cm, đoạn thẳng BC dài 19 cm. Hỏi cả hai đoạn thẳng dài bao nhiêu xăng-ti-mét?', kq: 29 },
     { class: 1, ex: ' Một thanh gỗ dài 85cm, Lan cắt đi 25cm. Hỏi thanh gỗ còn lại dài bao nhiêu xăng ti mét?', kq: 60 },


     //Class Two
     { class: 2, ex: 'Tìm một số, biết số đó cộng với 12 thì bằng 15 cộng 27?', kq: 30 },
     { class: 2, ex: 'Tìm một số, biết 95 trừ đi số đó thì bằng 39 trừ đi 22?', kq: 78 },
     { class: 2, ex: 'Hồng có nhiều hơn Hà 10 viên bi, nếu Hồng cho Hà 4 viên bi thì Hồng còn nhiều hơn Hà mấy viên bi?', kq: 2 },
     { class: 2, ex: 'Tìm y : 36 + 65 = y + 22 ', kq: 79 },
     { class: 2, ex: 'Tìm y :100 - 55 = y - 13', kq: 58 },
     { class: 2, ex: 'Tìm y :121 - 35 = y - 23', kq: 109 },
     { class: 2, ex: 'Tìm y :111 - 55 = y - 33', kq: 89 },
     { class: 2, ex: 'Tìm y :101 - 54 = y - 43', kq: 90 },
     { class: 2, ex: 'Tìm y :109 - 76 = y - 53', kq: 86 },
     { class: 2, ex: 'Tìm y :107 - 65 = y - 13', kq: 55 },
     { class: 2, ex: 'Tìm y :121 - 54 = y - 23', kq: 90 },
     { class: 2, ex: 'Tính : 5 + 5 + 5 + 5 + 5 + 5 = … ', kq: 30 },
     { class: 2, ex: 'Tính : 4 + 4 + 12 + 8 =…… ', kq: 28 },
     { class: 2, ex: 'Tính : 3 + 6 + 9 + 12 =… ', kq: 30 },
     { class: 2, ex: 'Tính : 65 + 92 + 35 + 7 =…… ', kq: 199 },
     { class: 2, ex: 'Tính : 73 + 73 + 13 + 10 =…… ', kq: 169 },
     { class: 2, ex: 'Tính : 78 + 43 + 34 + 9 =…… ', kq: 164 },
     { class: 2, ex: 'Tính : 79 + 56 + 29 + 8 =…… ', kq: 172 },
     { class: 2, ex: 'Tính : 93 + 76 + 19 + 11 =…… ', kq: 199 },
     { class: 2, ex: 'Tìm một số, biết rằng lấy số đó nhân với 5 rồi trừ đi 12 thì bằng 38?', kq: 10 },
     { class: 2, ex: 'Có một số dầu, nếu đựng vào các can mỗi can 4l thì đúng 6 can. Hỏi số dầu đó nếu đựng vào các can, mỗi can 3l thì phải dùng tất cả bao nhiêu can?', kq: 8 },
     { class: 2, ex: 'Có bao nhiêu số có hai chữ số bé hơn 54?....', kq: 44 },
     { class: 2, ex: 'Từ 57 đến 163 có bao nhiêu số có hai chữ số?(tính cả 57)', kq: 43 },
     { class: 2, ex: 'Có bao nhiêu số có ba chữ số lớn hơn 369?....', kq: 630 },
     { class: 2, ex: 'Hai số có hai chữ số ,có cùng chữ số hàng chục mà chữ số hàng đơn vị hơn kém nhau 7 thì hai số đó hơn kém nhau bao nhiêu đơn vị?', kq: 7 },
     { class: 2, ex: 'Hai số có hai chữ số ,có cùng chữ số hàng đơn vị mà chữ số hàng chục hơn kém nhau 3 thì số đó hơn kém nhau bao nhiêu đơn vị?', kq: 30 },
     { class: 2, ex: 'Biết số liền trước của a là 23, em hãy tìm số liền sau của a?', kq: 25 },
     { class: 2, ex: 'Biết số liền sau của b là 35, hãy tìm số liền trước của b?', kq: 33 },
     { class: 2, ex: 'Biết số c không có số liền trước, hỏi c là số nào?', kq: 0 },
     { class: 2, ex: 'Để đánh số các trang của một cuốn sách từ 1 đến 19, ta phải dùng hết bao nhiêu số?', kq: 19 },
     { class: 2, ex: 'Để đánh số các trang của một cuốn sách từ 10 đến 25, ta phải dùng hết bao nhiêu số?', kq: 16 },
     { class: 2, ex: 'Để đánh số các trang của một cuốn sách từ 120 đến 129, ta phải dùng hết bao nhiêu số?', kq: 10 },
     { class: 2, ex: 'Để đánh số các trang của một cuốn sách từ 111 đến 119, ta phải dùng hết bao nhiêu số?', kq: 9 },
     { class: 2, ex: 'Để đánh số các trang của một cuốn sách từ 191 đến 209, ta phải dùng hết bao nhiêu số?', kq: 18 },
     { class: 2, ex: 'Để đánh số các trang của một cuốn sách từ 91 đến 129, ta phải dùng hết bao nhiêu số?', kq: 38 },
     { class: 2, ex: 'Để đánh số các trang của một cuốn sách từ 100 đến 112, ta phải dùng hết bao nhiêu số?', kq: 13 },
     { class: 2, ex: 'Tìm chữ số x, biết:35x < 351', kq: 0 },
     { class: 2, ex: 'Tìm chữ số x, biết:207> x70 ', kq: 1 },
     { class: 2, ex: 'Tìm chữ số x, biết:199< xxx < 299 (chỉ nhập 1 số x)', kq: 2 },
     { class: 2, ex: 'Tổng lớn nhất của hai số có một chữ số là bao nhiêu?', kq: 18 },
     { class: 2, ex: 'Tìm một số, biết tổng của số đó với 45 bằng số bé nhất có ba chữ số?', kq: 55 },
     { class: 2, ex: 'Tìm một số, biết hiệu của 89 với số đó bằng 15?', kq: 74 },
     { class: 2, ex: 'Một ô tô chở khách dừng tại bến đỗ. Có 8 người xuống xe và 5 người lên xe. Xe tiếp tục chạy, lúc này trên xe có tất cả 50 hành khách. Hỏi trước khi xe dừng lại bến đỗ đó, trên xe có bao nhiêu hành khách?', kq: 53 },
     { class: 2, ex: 'Gói kẹo chanh và gói kẹo dừa có tất cả 258 cái kẹo. Riêng gói kẹo chanh có 118 cái. Hỏi: Gói kẹo dừa có bao nhiêu cái kẹo?', kq: 140 },
     { class: 2, ex: 'Hai đội bóng bàn, mỗi đội có 3 người chơi đấu bóng bàn với nhau. Mỗi người của đội này đều đấu một ván với mỗi người của đội kia. Hỏi có tất cả bao nhiêu ván đấu?', kq: 9 },
     { class: 2, ex: 'Con ngỗng cân nặng 11kg. Con ngỗng cân nặng hơn con vịt 8 kg. Con gà cân nặng ít hơn con vịt 2 kg. Hỏi con ngỗng cân nặng hơn con gà mấy kg?', kq: 10 },
     { class: 2, ex: 'Trên bãi cỏ có 15 con bò. Số bò nhiều hơn số trâu là 10 con. Số cừu bằng số bò và trâu cộng lại. Hỏi trên bãi cỏ có Tất cả có bao nhiêu con?', kq: 40 },
     { class: 2, ex: 'Một thúng đựng 56 quả vừa trứng gà vừa trứng vịt. Mẹ đã bán 25 quả trứng gà, trong thúng còn 12 quả trứng gà nữa. Hỏi lúc đầu trong thúng có bao nhiêu quả trứng vịt?', kq: 19 },
     { class: 2, ex: 'Năm nay con 8 tuổi, mẹ 32 tuổi. Hỏi trước đây 2 năm tuổi mẹ cộng với tuổi con là bao nhiêu?', kq: 36 },
     { class: 2, ex: 'Hiện nay Mai 7 tuổi, Hoa 10 tuổi, Hồng 9 tuổi. Đến khi Bạn Mai bằng tuổi bạn Hồng hiện nay thì tổng số tuổi của ba bạn là bao nhiêu?', kq: 32 },
     { class: 2, ex: 'Đặt tính rồi tính :36 + 23', kq: 59 },
     { class: 2, ex: 'Đặt tính rồi tính :100 – 46 ', kq: 54 },
     { class: 2, ex: 'Đặt tính rồi tính :60 + 27 ', kq: 87 },
     { class: 2, ex: 'Đặt tính rồi tính :72 – 19 ', kq: 53 },
     { class: 2, ex: 'Đặt tính rồi tính :57 + 38 ', kq: 95 },
     { class: 2, ex: 'Đặt tính rồi tính :98 – 49 ', kq: 49 },
     { class: 2, ex: 'Đặt tính rồi tính :100 – 60 ', kq: 40 },
     { class: 2, ex: 'Đặt tính rồi tính :45 + 59 ', kq: 104 },
     { class: 2, ex: 'Đặt tính rồi tính :67 + 23 ', kq: 90 },
     { class: 2, ex: 'Đặt tính rồi tính :18 + 35 ', kq: 53 },
     { class: 2, ex: 'Đặt tính rồi tính : 76 – 37 ', kq: 39 },
     { class: 2, ex: 'Đặt tính rồi tính :81 – 37 ', kq: 44 },
     { class: 2, ex: 'Đặt tính rồi tính :21 + 29 ', kq: 50 },
     { class: 2, ex: 'Đặt tính rồi tính :57 – 48 ', kq: 9 },
     { class: 2, ex: 'Đặt tính rồi tính :32 : 8 ', kq: 4 },
     { class: 2, ex: 'Đặt tính rồi tính :9 x 4   ', kq: 36 },
     { class: 2, ex: 'Đặt tính rồi tính :40 : 4  ', kq: 10 },
     { class: 2, ex: 'Đặt tính rồi tính :50 : 10 ', kq: 5 },
     { class: 2, ex: 'Đặt tính rồi tính :24 : 6 ', kq: 4 },
     { class: 2, ex: 'Đặt tính rồi tính :27 : 9 ', kq: 3 },
     { class: 2, ex: 'Đặt tính rồi tính :21 : 3 ', kq: 7 },
     { class: 2, ex: 'Đặt tính rồi tính :35 : 5 ', kq: 7 },
     { class: 2, ex: 'Đặt tính rồi tính :12 : 6 ', kq: 2 },
     { class: 2, ex: 'Đặt tính rồi tính : 15 : 3 ', kq: 5 },
     { class: 2, ex: 'Đặt tính rồi tính :18 : 6 ', kq: 3 },
     { class: 2, ex: 'Đặt tính rồi tính : 20 : 4 ', kq: 5 },
     { class: 2, ex: 'Đặt tính rồi tính :26 : 4  ', kq: 6 },
     { class: 2, ex: 'Đặt tính rồi tính :18 : 9 ', kq: 2 },
     { class: 2, ex: 'Đặt tính rồi tính :3 x 8  ', kq: 24 },
     { class: 2, ex: 'Đặt tính rồi tính :4 x 7 ', kq: 28 },
     { class: 2, ex: 'Đặt tính rồi tính : 6 x 5  ', kq: 30 },
     { class: 2, ex: 'Đặt tính rồi tính :9 x 5   ', kq: 45 },
     { class: 2, ex: 'Đặt tính rồi tính :8 x 4 ', kq: 32 },
     { class: 2, ex: 'Đặt tính rồi tính :9x 2 ', kq: 18 },
     { class: 2, ex: 'Đặt tính rồi tính : 6 x 3 ', kq: 18 },
     { class: 2, ex: 'Đặt tính rồi tính :3 x 4  ', kq: 12 },
     { class: 2, ex: 'Đặt tính rồi tính :9 x 3  ', kq: 27 },
     { class: 2, ex: 'Đặt tính rồi tính :7 x 5 ', kq: 35 },
     { class: 2, ex: 'Đặt tính rồi tính :10 x 3 ', kq: 30 },
     { class: 2, ex: 'Điền số : 2 dm 8cm = ……cm', kq: 28 },
     { class: 2, ex: 'Điền số : 90dm = ………cm', kq: 900 },
     { class: 2, ex: 'Điền số : 32dm 3cm =…cm', kq: 323 },
     { class: 2, ex: 'Điền số :  8dm = ……cm', kq: 80 },
     { class: 2, ex: 'Tìm x :x +17 = 90 – 9 ', kq: 64 },
     { class: 2, ex: 'Tìm x :71 – x = 17 + 12', kq: 42 },
     { class: 2, ex: 'Tìm x :3 x x = 12 + 18 ', kq: 10 },
     { class: 2, ex: 'Tìm x :x : 4 = 36 : 9 ', kq: 16 },
     { class: 2, ex: 'Tìm x :28 : x = 65 – 58  ', kq: 4 },
     { class: 2, ex: 'Tìm x :7 x x = 81 – 60 ', kq: 3 },
     { class: 2, ex: 'Tìm x :x + 3 = 15  ', kq: 12 },
     { class: 2, ex: 'Tìm x :9 + x = 15', kq: 6 },
     { class: 2, ex: 'Tìm x :x – 14 = 37 ', kq: 51 },
     { class: 2, ex: 'Tìm x : 89 – x = 67', kq: 22 },
     { class: 2, ex: 'Tìm x :x + 39 = 60', kq: 21 },
     { class: 2, ex: 'Tìm x :48 + x = 65 ', kq: 17 },
     { class: 2, ex: 'Tìm x :x – 34 = 29 ', kq: 63 },
     { class: 2, ex: 'Tìm x :73 – x = 45', kq: 28 },
     { class: 2, ex: 'Toàn có 26 viên bi, Toàn có nhiều hơn Nam 9 viên bi. Hỏi Nam có bao nhiêu viên bi?', kq: 17 },
     { class: 2, ex: 'Mỗi con vịt có 2 cái chân. Hỏi 7 con vịt có bao nhiêu cái chân?', kq: 14 },
     { class: 2, ex: ' Mỗi xe đạp có 2 bánh. Hỏi 5 xe đạp như thế có bao nhiêu bánh xe?', kq: 10 },
     { class: 2, ex: 'Tính nhẩm :3 x 7 = ', kq: 21 },
     { class: 2, ex: 'Tính nhẩm :18 : 2 =   ', kq: 9 },
     { class: 2, ex: 'Tính nhẩm :4 x 6 =', kq: 24 },
     { class: 2, ex: 'Tính nhẩm :16 : 4 =', kq: 4 },
     { class: 2, ex: 'Tính nhẩm :4 x 8 =', kq: 32 },
     { class: 2, ex: 'Tính nhẩm :28 : 4 = ', kq: 7 },
     { class: 2, ex: 'Tính nhẩm :3 x 4 = ', kq: 12 },
     { class: 2, ex: 'Tính nhẩm :20 : 2 =', kq: 10 },
     { class: 2, ex: 'Tính nhẩm :5 x 5 =', kq: 25 },
     { class: 2, ex: 'Tính nhẩm :15 : 3 = ', kq: 5 },
     { class: 2, ex: 'Tính nhẩm : 5 x 2 = ', kq: 10 },
     { class: 2, ex: 'Tính nhẩm :30 : 3 =', kq: 10 },
     { class: 2, ex: 'Có 24 học sinh chia đều thành 3 tổ. Hỏi mỗi tổ có mấy học sinh?', kq: 8 },
     { class: 2, ex: 'Mỗi chuồng có 5 con thỏ. Hỏi 4 chuồng như thế có tất cả bao nhiêu con thỏ?', kq: 20 },
     { class: 2, ex: 'Biết thỏ ít hơn gà 18 con và số thỏ là 19 con. Hỏi cả gà và thỏ có bao nhiêu con?', kq: 56 },
     { class: 2, ex: 'An cho Bình 16 viên bi, An còn lại 26 viên bi. Hỏi trước khi cho Bình thì An có bao nhiêu viên bi ?', kq: 42 },
     { class: 2, ex: 'Tuổi của Bố hiện nay 35 tuổi, con là 12 tuổi.Tính tổng số tuổi của con và bố khi con bằng tuổi bố.', kq: 93 },
     { class: 2, ex: 'Tuổi của Anh hiện nay là 45 tuổi , em là 37 tuổi .Tính tổng số tuổi của 2 anh em khi tuổi em bằng tuổi anh.', kq: 98 },
     { class: 2, ex: 'Có 1 lượng gạo, khi cho vào mỗi túi 4 kg thì được 10 túi. Hỏi cũng lượng gạo đó cho vào mỗi túi 5kg thì được bao nhiêu túi.', kq: 8 },
     { class: 2, ex: 'Có 1 lượng gạo, khi cho vào mỗi túi 3kg thì được 11 túi và còn thừa 2kg. Hỏi lượng gạo đó là bao nhiêu kg?', kq: 35 },
     { class: 2, ex: 'Có 1 lượng gạo, khi cho vào mỗi túi 5kg thì được 8 túi và còn thừa 4kg. Hỏi lượng gạo đó là bao nhiêu kg?', kq: 44 },
     { class: 2, ex: 'Có 1 lượng dầu, khi cho vào mỗi thùng 5 lít thì được 6 thùng. Hỏi cũng lượng dầu đó cho vào mỗi thùng 3 lít thì được bao nhiêu thùng?', kq: 10 },
     { class: 2, ex: 'Bình có nhiều hơn An 11 viên bi. Nếu Bình cho An 6 viên bi thì Bình ít hơn An mấy viên bi?', kq: 1 },
     { class: 2, ex: 'Mai có nhiều hơn Nam 12 viên bi. Hỏi Mai phải cho Nam bao nhiêu viên bi để 2 bạn có số bi bằng nhau?', kq: 6 },
     { class: 2, ex: 'Linh có nhiều hơn Hà 13 viên bi. Nếu Linh cho Hà 5 viên bi thì số bi Linh còn nhiều hơn Hà là bao nhiêu viên?', kq: 3 },
     { class: 2, ex: 'Lan có nhiều hơn Huệ 12 quyển vở. Hồng cho Huệ 4 quyển vở. Hỏi Lan còn nhiều hơn Huệ bao nhiêu quyển vở.', kq: 8 },
     { class: 2, ex: 'An có nhiều hơn Dũng 1 số viên bi. Nếu An cho Dũng 8 viên bi thì hai bạn có số bi bằng nhau. Hỏi An có nhiều Dũng bao nhiêu viên bi?', kq: 16 },
     { class: 2, ex: 'An có 1 số hộp bi, mỗi hộp 5 viên. An mua thêm 30 bi nữa. Hỏi An có thêm được bao nhiêu hộp bi?', kq: 6 },

     //Class Three
     { class: 3, ex: 'Lớp 2A có 34 học sinh, lớp 2B có 29 học sinh. Tính tổng số học sinh của hai lớp 2A và 2B.', kq: 63 },
     { class: 3, ex: 'An có 29 cái kẹo, mẹ cho An 5 cái kẹo. Hỏi lúc này An có tất cả bao nhiêu cái kẹo?', kq: 34 },
     { class: 3, ex: 'Lớp 2A có 19 bạn nam và 18 bạn nữ. Hỏi lớp 2A có tất cả bao nhiêu học sinh.', kq: 37 },
     { class: 3, ex: 'Trên sân có 18 con vịt và 14 con gà. Hỏi trên sân có tất cả bao nhiêu con cả gà và vịt?', kq: 32 },
     { class: 3, ex: 'Khúc gỗ thứ nhất dài 17dm, khúc gỗ thứ hai dài 19dm. Nếu khúc gỗ thứ ba bằng tổng độ dài hai khúc gỗ đầu thì khúc gỗ thứ ba dài bao nhiêu đề-xi-mét?', kq: 36 },
     { class: 3, ex: 'Tìm số lớn nhất có hai chữ số mà tổng hai chữ số bằng 11', kq: 92 },
     { class: 3, ex: 'Tìm hiệu của 98 với số lớn nhất có tổng hai chữ số là 11.', kq: 6 },
     { class: 3, ex: 'x + 21= 26 + 15', kq: 20 },
     { class: 3, ex: '22 + x = 39 + 36', kq: 53 },
     { class: 3, ex: 'x + 33 = 37 + 38', kq: 42 },
     { class: 3, ex: '51 + x = 46 + 35', kq: 30 },
     { class: 3, ex: 'một máy bơm hoạt động hết công suất thì có thể bơm được 150 m3 nước trong 1 giờ, hỏi 1 bể nước chưa 7200 m3 nước thì máy bơm phải hoạt động trong mấy ngày thì xong công việc ', kq: 2 },
     { class: 3, ex: 'Thái có a viên bi xanh và b viên bi đỏ, a Giang cho thái thêm 3 viên bi đỏ nữa thì lúc này số bi đỏ của thái gấp đôi số bi xanh, hỏi số bi đỏ ban đầu của Thái có là bao nhiêu viên, biết rằng ban đầu thái có 24 viên bi ? ', kq: 15 },
     { class: 3, ex: 'Thái được mẹ cho 100.000đ để đi chợ mua thức ăn, Thái mua rau hết 24.000đ, mua Thịt lợn hết xđ , cuối cùng Thái mua thêm trứng hết 36.000đ, biết rằng Thái phải về xin mẹ thêm 24.000đ để trả tiền trứng. Hỏi thái mua thịt hết bao nhiêu tiền ?', kq: 64 },
     { class: 3, ex: 'Biết tổng 2 số bằng 31 , số lớn hơn số bé là 1 đơn vị. hỏi số lớn bằng bao nhiêu', kq: 16 },
     { class: 3, ex: 'Biết số lớn gấp đôi số bé, và hiệu 2 số là 10, hỏi số bé bằng bao nhiêu', kq: 10 },
     { class: 3, ex: 'Thái đi chợ mua a quả trứng gà và b quả trứng vịt, không may Thái làm vỡ 3 quả trứng gà thì lúc này số trứng gà và trứng vịt lại bằng nhau, và tổng số trứng trong giỏ lú này là 30 quả, hỏi số trứng gà mà thái đã mua lúc đầu', kq: 18 },
     { class: 3, ex: 'Tìm số tự nhiên có 2 chữ số biết chữ số hàng chục gấp 5 lần chữ số hàng đơn vị, và tổng của chữ số hàng chục và hàng đơn vị là 6, Hỏi khi lấy số này trừ đi 50 thì được bao nhiêu?', kq: 1 },
     { class: 3, ex: 'Tìm số tự nhiên có 2 chữ số biết chữ số hàng chục gấp 7 lần chữ số hàng đơn vị, và hiệu của chữ số hàng chục và hàng đơn vị là 6, Hỏi khi lấy số này trừ đi 50 thì được bao nhiêu? ', kq: 21 },
     { class: 3, ex: 'Thái đi mua hoa quả. Thái mua được 2 loại là Cam và Ôỉ, hết tổng cộng 125.000đ, biết Thái mua được 5 quả cam với giá 10.000đ 1 quả, hỏi Thái mua được bao nhiêu quả ổi, biết giá ổi bằng 1 nửa giá cam ', kq: 15 },
     { class: 3, ex: 'Tìm số tự nhiên có 2 chữ số biết, chữ số hàng đơn vị gấp 8 lần chữ số hàng chục, và số này chia hết cho 3 ?', kq: 18 },
     { class: 3, ex: 'Tìm số tự nhiên có 2 chữ số biết rằng chữ số hàng chục gấp 8 lần chữ số hàng đơn vị và số này chia hết cho 9 ?', kq: 81 },
     { class: 3, ex: 'Lớp Thái có 12 học sinh giỏi Toán, số học sinh giỏi văn gấp đôi số học sinh giỏi toán, Và số học sinh giỏi Anh bằng 1 nửa tổng số học sinh giỏi Văn và Toán cộng lại,Hỏi số học sinh giỏi Anh là bao nhiêu bạn', kq: 18 },
     { class: 3, ex: 'Lớp Thái có 18 học sinh giỏi Toán, số học sinh giỏi văn gấp đôi số học sinh giỏi toán, Và số học sinh giỏi Anh bằng 1 nửa tổng số học sinh giỏi Văn và Toán cộng lại,Hỏi số học sinh giỏi Anh là bao nhiêu bạn', kq: 27 },
     { class: 3, ex: 'Lớp Thái có 10 học sinh giỏi Toán, số học sinh giỏi văn gấp đôi số học sinh giỏi toán, Và số học sinh giỏi Anh bằng 1 nửa tổng số học sinh giỏi Văn và Toán cộng lại,Hỏi số học sinh giỏi Anh là bao nhiêu bạn', kq: 15 },
     { class: 3, ex: 'Lớp Thái có 8 học sinh giỏi Toán, số học sinh giỏi văn gấp đôi số học sinh giỏi toán, Và số học sinh giỏi Anh bằng 1 nửa tổng số học sinh giỏi Văn và Toán cộng lại,Hỏi số học sinh giỏi Anh là bao nhiêu bạn', kq: 12 },
     { class: 3, ex: 'Lớp Thái có 4 học sinh giỏi Toán, số học sinh giỏi văn gấp đôi số học sinh giỏi toán, Và số học sinh giỏi Anh bằng 1 nửa tổng số học sinh giỏi Văn và Toán cộng lại,Hỏi số học sinh giỏi Anh là bao nhiêu bạn', kq: 6 },

     { class: 3, ex: 'Tìm 1 số tự nhiên biết rằng nếu lấy số đó cộng thêm 5 đơn vị sẽ được số gấp 10 lần số 5.', kq: 45 },
     { class: 3, ex: 'Tìm 1 số tự nhiên biết rằng nếu lấy số đó cộng thêm 7 đơn vị sẽ được số gấp 7 lần số 9.', kq: 56 },
     { class: 3, ex: 'Tìm 1 số tự nhiên biết rằng nếu lấy số đó trừ đi 23 đơn vị sẽ được số gấp 12 lần số 14.', kq: 191 },
     { class: 3, ex: 'Tìm 1 số tự nhiên biết rằng nếu lấy số đó trừ đi 19 đơn vị sẽ được số gấp 28 lần số 9.', kq: 271 },
     { class: 3, ex: 'Tìm 1 số tự nhiên biết rằng nếu lấy số đó cộng thêm 16 đơn vị sẽ được số gấp 9 lần số 25.', kq: 209 },
     { class: 3, ex: 'Một sợi dây dài 9135 cm được cắt thành 2 đoạn. Đoạn thứ nhất dài bằng 1/7 chiều dài sợi dây. Tính độ dài đoạn dài hơn ?', kq: 7830 },
     { class: 3, ex: 'Một thùng đựng 84 lít mật ong, người ta đã lấy ra 1/3 số lít mật ong đó. Hỏi trong thùng còn lại bao nhiêu lít mật ong?', kq: 56 },
     { class: 3, ex: 'Một cửa hàng có 1242 cái áo, cửa hàng đã bán 1/6 số áo. Hỏi cửa hàng đó còn lại bao nhiêu cái áo?', kq: 1035 },
     { class: 3, ex: 'Thùng thứ nhất đựng 35 lít dầu, thùng thứ hai đựng nhiều hơn thùng thứ nhất 15 lít dầu. Hỏi cả hai thùng đựng bao nhiêu lít dầu?', kq: 85 },
     { class: 3, ex: 'Anh có 56 viên bi, em có ít hơn anh 12 viên bi. Hỏi cả hai anh em có bao nhiêu viên bi?', kq: 100 },
     { class: 3, ex: 'Lớp 3A trồng được 42 cây, lớp 3B trồng được gấp 4 lần số cây của lớp 3A. hỏi cả hai lớp trồng được bao nhiêu cây?', kq: 210 },
     { class: 3, ex: 'Một bến xe có 76 ô tô. Lúc đầu có 18 ô tô rời bến, sau đó có thêm 16 ô tô nữa rời bến. Hỏi bến xe đó còn lại bao nhiêu ô tô?', kq: 42 },
     { class: 3, ex: 'Có 5 thùng dầu, mỗi thùng chứa 120 lít. Người ta đã lấy ra 130 lít từ số dầu đó. Hỏi còn lại bao nhiêu lít dầu?', kq: 470 },
     { class: 3, ex: 'Can thứ nhất có 18 lít dầu. Số dầu ở can thứ hai gấp 3 lần số dầu ở can thứ nhất. hỏi can thứ hai nhiều hơn can thư nhất bao nhiêu lít dầu?', kq: 36 },
     { class: 3, ex: ' Một tổ công nhân buổi sáng sửa được 24m. buổi chiều do trời nắng nên sửa được số mét đường giảm đi 3 lần so với buổi sáng. Hỏi buổi chiều tổ công nhân đó sửa được mấy mét đường?', kq: 8 },
     { class: 3, ex: 'Một nhóm khách du lịch mang theo 4 bình, mỗi bình 2 lít nước và một bình 5 lít nước. Hỏi nhóm đó mang theo bao nhiêu lít nước?', kq: 11 },
     { class: 3, ex: 'Một nhóm khách du lịch mang theo 9 bình, mỗi bình 7 lít nước và một bình 8 lít nước và 3 bình 10 lít. Hỏi nhóm đó mang theo bao nhiêu lít nước?', kq: 73 },
     { class: 3, ex: 'Người ta chia khu vườn ươm cây thành 2 lô đất, mỗi lô đất có 4 hàng, mỗi hàng trồng 105 cây con. Hỏi khu vườn đó trồng được bao nhiêu cây con?', kq: 840 },
     { class: 3, ex: 'Cô giáo có 45 cái bút thưởng đều cho 5 tổ. Hỏi mỗi tổ được thưởng bao nhiêu cái bút?', kq: 9 },
     { class: 3, ex: 'Một đội công nhân phải làm xong con đường dài 24 m. Mỗi ngày đội công nhân làm được 6m. Hỏi đội công nhân làm xong con đường trong bao nhiêu ngày?', kq: 4 },
     { class: 3, ex: ' Một đội công nhân phải làm xong con mương dài 32 m. Mỗi ngày đội công nhân làm được 8 m. Hỏi đội công nhân làm xong con mương trong bao nhiêu ngày?', kq: 4 },
     { class: 3, ex: 'Một đội công nhân phải làm xong con đường dài 21 m trong 7 ngày. Hỏi mỗi ngày đội công nhân phải làm bao nhiêu mét đường?', kq: 3 },
     { class: 3, ex: 'Một đàn gà có 88 con, số gà trắng và bằng 7 lần số gà đen. Hỏi đàn gà có bao nhiêu con gà đen?', kq: 11 },
     { class: 3, ex: 'Cửa hàng buổi sáng bán được 77 xe đạp và gấp bảy lần số xe đạp bán được trong buổi chiều. Hỏi cửa hàng bán được bao nhiêu xe đạp vào buổi chiều?', kq: 11 },
     { class: 3, ex: 'Trong đội đồng ca của một trường tiểu học có 100 bạn nam và gấp năm lần số bạn nữ. Hỏi đội đồng ca có bao nhiêu bạn nữ?', kq: 20 },
     { class: 3, ex: 'Một cửa hàng buổi sáng bán được 13 kg đường. Buổi chiều bán được số đường gấp ba lần số đường bán được vào buổi sáng. Hỏi cả hai buổi cửa hàng bán được bao nhiêu ki-lô-gam đường?', kq: 52 },
     { class: 3, ex: 'Một cửa hàng ngày thứ nhất bán được 28 lít dầu. Số dầu ngày thứ hai bán được bằng 1/7 số dầu bán được của ngày thứ nhất. Hỏi cả hai ngày cửa hàng bán được bao nhiêu lít dầu?', kq: 32 },
     { class: 3, ex: 'Băng giấy đỏ dài 25 cm, băng giấy xanh ngắn hơn băng giấy đỏ 14 cm. Hỏi cả hai băng giấy dài bao nhiêu xăng-ti-mét?', kq: 36 },
     { class: 3, ex: 'Một cửa hàng ngày thứ nhất bán được 64 lít dầu. Số dầu ngày thứ hai bán được bằng 1/8 số dầu bán được của ngày thứ nhất. Hỏi cả hai ngày cửa hàng bán được bao nhiêu lít dầu?', kq: 72 },
     { class: 3, ex: 'Một cửa hàng buổi sáng bán được 26 kg đường. Số đường buổi sáng bán được ít hơn số đường bán trong buổi chiều là 26 kg. Hỏi cả hai buổi cửa hàng bán được bao nhiêu ki-lô-gam đường?', kq: 78 },
     { class: 3, ex: 'Trong vườn của bác Nam có 66 cây bưởi, số cây chuối bằng 1/6 số cây bưởi. Hỏi trong vườn nhà bác Nam có bao nhiêu cây bưởi và chuối?', kq: 77 },
     { class: 3, ex: 'Một cửa hàng buổi sáng bán được 17 kg đường. Số đường buổi sáng bán được ít hơn số đường bán trong buổi chiều là 51 kg. Hỏi cả hai buổi cửa hàng bán được bao nhiêu ki-lô-gam đường?', kq: 85 },
     { class: 3, ex: 'Một cửa hàng buổi sáng bán được 49 kg đường. Số đường buổi sáng bán được nhiều hơn số đường bán trong buổi chiều 32 kg. Hỏi cả hai buổi cửa hàng bán được bao nhiêu ki-lô-gam đường?', kq: 66 },
     { class: 3, ex: 'Một cửa hàng ngày thứ nhất bán được 34 lít dầu. Số dầu ngày thứ hai bán được bằng 1/2 số dầu bán được của ngày thứ nhất. Hỏi cả hai ngày cửa hàng bán được bao nhiêu lít dầu?', kq: 51 },
     { class: 3, ex: 'Ngăn trên có 32 quyển sách. Số quyển sách ở ngăn dưới bằng 1/4 số quyển ở ngăn trên. Hỏi cả hai ngăn có bao nhiêu quyển sách?', kq: 40 },
     { class: 3, ex: 'Tổ một gấp được 28 cái thuyền, tổ hai gấp được gấp được nhiều hơn tổ một 11 cái thuyền. Hỏi cả hai tổ gấp được bao nhiêu cái thuyền?', kq: 67 },
     { class: 3, ex: 'Đàn gà có 40 gà trống, số gà mái bằng 1/8 số gà trống. Hỏi đàn gà có tất cả bao nhiêu con?', kq: 45 },
     { class: 3, ex: 'Một cửa hàng ngày thứ nhất bán được 30 lít dầu. Số dầu bán được của ngày thứ nhất ít hơn số dầu bán được của ngày thứ hai 21 lít. Hỏi cả hai ngày cửa hàng bán được bao nhiêu lít dầu?', kq: 81 },
     { class: 3, ex: 'Ngăn trên có 56 quyển sách. Số quyển sách ở ngăn dưới bằng 1/8 số quyển ở ngăn trên. Hỏi cả hai ngăn có bao nhiêu quyển sách?', kq: 63 },
     { class: 3, ex: 'Ngăn trên có 36 quyển sách. Số sách ở ngăn trên ít hơn số sách ở ngăn dưới 20 quyển. Hỏi cả hai ngăn có bao nhiêu quyển sách?', kq: 92 },
     { class: 3, ex: ' Một cửa hàng ngày thứ nhất bán được 68 lít dầu. Số dầu ngày thứ hai bán được bằng 1/4 số dầu bán được của ngày thứ nhất. Hỏi cả hai ngày cửa hàng bán được bao nhiêu lít dầu?', kq: 85 },
     { class: 3, ex: 'Băng giấy đỏ dài 3 cm, băng giấy vàng dài gấp bảy lần băng giấy đỏ. Hỏi cả hai băng giấy dài bao nhiêu xăng-ti-mét?', kq: 24 },
     { class: 3, ex: 'Đội đồng ca của lớp 1A có 69 nữ, số bạn nam bằng 1/3 số bạn nữ. Hỏi đội đồng ca của lớp 1A có bao nhiêu em?', kq: 92 },
     { class: 3, ex: 'Tổ một gấp được 23 cái thuyền, tổ hai gấp được gấp được nhiều hơn tổ một 54 cái thuyền. Hỏi cả hai tổ gấp được bao nhiêu cái thuyền?', kq: 100 },
     { class: 3, ex: 'Một cửa hàng buổi sáng bán được 56 kg đường. Số đường buổi sáng bán được nhiều hơn số đường bán trong buổi chiều 27 kg. Hỏi cả hai buổi cửa hàng bán được bao nhiêu ki-lô-gam đường?', kq: 85 },
     { class: 3, ex: 'Một cửa hàng ngày thứ nhất bán được 36 lít dầu. Số dầu ngày thứ hai bán được bằng 1/6 số dầu bán được của ngày thứ nhất. Hỏi cả hai ngày cửa hàng bán được bao nhiêu lít dầu?', kq: 42 },
     { class: 3, ex: 'Một cửa hàng ngày thứ nhất bán được 49 lít dầu. Số dầu bán được của ngày thứ nhất nhiều hơn số dầu bán được của ngày thứ hai 33 lít. Hỏi cả hai ngày cửa hàng bán được bao nhiêu lít dầu?', kq: 65 },
     { class: 3, ex: 'Trong vườn của bác Nam có 7 cây bưởi, số cây chuối nhiều hơn số cây bưởi 22 cây. Hỏi trong vườn nhà bác Nam có bao nhiêu cây bưởi và chuối?', kq: 36 },
     { class: 3, ex: 'Đội đồng ca có 6 nữ, số bạn nam nhiều hơn số bạn nữ là 83 em. Hỏi đội đồng ca có bao nhiêu em?', kq: 95 },
     { class: 3, ex: 'Băng giấy đỏ dài 9 cm, băng giấy vàng dài gấp ba lần băng giấy đỏ. Hỏi cả hai băng giấy dài bao nhiêu xăng-ti-mét?', kq: 36 },
     { class: 3, ex: 'Đàn gà có 44 gà trống, số gà mái nhiều hơn số gà trống là 10 con. Hỏi đàn gà có tất cả bao nhiêu con?', kq: 98 },
     { class: 3, ex: 'Băng giấy đỏ dài 33 cm, băng giấy xanh dài hơn băng giấy đỏ 12 cm. Hỏi cả hai băng giấy dài bao nhiêu xăng-ti-mét?', kq: 78 },
     { class: 3, ex: 'Mỹ hái được 38 bông hoa. Số bông hoa Linh hái được bằng 1/2 số hoa Mỹ hái được. Hỏi hai bạn hái được tất cả bao nhiêu bông hoa?', kq: 57 },
     { class: 3, ex: 'Mỹ hái được 4 bông hoa. Số bông hoa Linh hái được gấp sáu lần số hoa Mỹ hái được. Hỏi hai bạn hái được tất cả bao nhiêu bông hoa?', kq: 28 },
     { class: 3, ex: 'Đội đồng ca của lớp 1A có 66 nữ, số bạn nam bằng 1/6 số bạn nữ. Hỏi đội đồng ca của lớp 1A có bao nhiêu em?', kq: 77 },
     { class: 3, ex: 'Một cửa hàng buổi sáng bán được 75 kg đường. Buổi chiều bán được số đường bằng 1/3 số đường bán được vào buổi sáng. Hỏi cả hai buổi cửa hàng bán được bao nhiêu ki-lô-gam đường?', kq: 100 },
     { class: 3, ex: 'Có 90 viên thuốc chứa đều trong 9 vỉ. Hỏi 6 vỉ thuốc đó có bao nhiêu viên thuốc?', kq: 60 },
     { class: 3, ex: 'Có 7 quyển vở được xếp đều vào 7 ngăn. Hỏi 6 ngăn đó có bao nhiêu quyển vở?', kq: 6 },
     { class: 3, ex: 'Mua 7 quyển vở hết 49 đồng. Hỏi mua 9 quyển vở như thế thì hết bao nhiêu tiền?', kq: 63 },
     { class: 3, ex: 'Có một số can như nhau để dựng dầu, biết 5 can đựng được 40 lít dầu. Hỏi 4 can như vậy đựng được bao nhiêu lít?', kq: 32 },
     { class: 3, ex: 'Cứ 9 con voi ăn hết 90 kg mía trong một tháng. Hỏi đàn voi có 2 con ăn hết bao nhiêu ki-lô-gam trong một tháng?', kq: 20 },
     { class: 3, ex: 'Có 60 viên thuốc chứa đều trong 3 vỉ. Hỏi một vỉ thuốc đó có bao nhiêu viên thuốc?', kq: 20 },
     { class: 3, ex: 'Cứ 4 học sinh trồng được 36 cây. Hỏi 2 học sinh trồng được bao nhiêu cây?', kq: 18 },
     { class: 3, ex: ' Cứ 3 quyển vở mua hết 27 đồng. Hỏi nếu có 18 đồng thì mua được bao nhiêu quyển vở?', kq: 2 },
     { class: 3, ex: ' 92 nghìn đồng mua được 4 gói kẹo. Hỏi nếu mua 8 gói kẹo như thế thì hết bao nhiêu nghìn đồng?', kq: 184 },
     { class: 3, ex: 'Có một số can như nhau để dựng dầu, biết 5 can đựng được 15 lít dầu. Hỏi 8 can như vậy đựng được bao nhiêu lít?', kq: 24 },
     { class: 3, ex: 'Một bếp ăn của đội công nhân mua về 3 kg gạo để nấu ăn trong 3 ngày. Hỏi 2 ngày nấu hết bao nhiêu ki-lô-gam gạo, biết rằng mỗi ngày nấu số gạo như nhau?', kq: 2 },
     { class: 3, ex: 'Cứ 7 con voi ăn hết 91 kg mía trong một tháng. Hỏi đàn voi có 5 con ăn hết bao nhiêu ki-lô-gam trong một tháng?', kq: 65 },
     { class: 3, ex: ' 3 ô tô chở được 21 cái máy tiện. Hỏi 8 ô tô như vậy chở được bao nhiêu cái máy tiện?', kq: 56 },
     { class: 3, ex: 'Cứ 6 quyển vở mua hết 12 đồng. Hỏi nếu có 6 đồng thì mua được bao nhiêu quyển vở?', kq: 3 },
     { class: 3, ex: ' 76 nghìn đồng mua được 2 gói kẹo. Hỏi nếu mua 8 gói kẹo như thế thì hết bao nhiêu nghìn đồng?', kq: 304 },
     { class: 3, ex: 'An có 72 viên kẹo đựng trong 6 túi, An cho bạn 2 túi. Hỏi An còn bao nhiêu viên kẹo.', kq: 48 },
     { class: 3, ex: 'Tính nhanh : 38 + 42 + 46 + 50 + 54 + 58 + 62', kq: 350 },
     { class: 3, ex: 'Tính nhanh : 11 + 137 + 72 + 63 + 128 + 89.', kq: 500 },
     { class: 3, ex: 'Tính nhanh : 15 x 2 + 15 x3 + 15 x5 – 100', kq: 50 },
     { class: 3, ex: 'Tính nhanh : 60 + 65 + 70 + 75 + 80 + 85 + 90 + 95', kq: 620 },
     { class: 3, ex: 'Tìm X : 64:X = 21 (dư 1)', kq: 3 },
     { class: 3, ex: 'Tìm X : X:6 = 7 (dư 3)', kq: 45 },
     { class: 3, ex: 'Tìm X : 85:X= 9 (dư 4)', kq: 9 },
     { class: 3, ex: 'Tìm X : 52:X= 5 (dư 2)', kq: 10 },
     { class: 3, ex: 'Mẹ tôi năm nay 38 tuổi. 2 năm nữa, tuổi em tôi bằng 1/4 tuổi mẹ. Vậy năm  nay, em tôi bao nhiêu tuổi.', kq: 8 },
     { class: 3, ex: 'An có 27 quyển truyện tranh, Bình có 19 quyển truyện tranh. Dũng có nhiều hơn Bình 12 quyển truyện tranh. Hỏi Dũng có nhiều hơn An bao nhiêu quyển?', kq: 4 },
     { class: 3, ex: 'Năm nay mẹ tôi 38 tuổi. Sang năm tuổi anh tôi bằng 1/3 tuổi mẹ. Hỏi mẹ tôi sinh anh tôi năm bao nhiêu tuổi?', kq: 26 },
     { class: 3, ex: 'Cho hình vuông có cạnh dài 3 cm. Tính chu vi hình vuông? ', kq: 12 },
     { class: 3, ex: 'Có 8 bao gạo đựng tất cả 448 kg gạo. Hỏi có 5 bao gạo như thế nặng bao nhiêu kg?', kq: 280 },
     { class: 3, ex: 'Một cửa hàng có 6 thùng nước mắm như nhau chứa tổng cộng 54 lít. Cửa hàng đã bán hết 36 lít. Hỏi cửa hàng còn lại bao nhiêu lít nước mắm.', kq: 18 },
     { class: 3, ex: ' Lúc đầu có 5 xe tải chở tổng cộng 210 bao đường vào kho, sau đó có thêm 3 xe nữa chở đường vào kho. Hỏi có tất cả bao nhiêu bao đường được chở vào kho? (Biết các xe tải chở số bao đường bằng nhau)', kq: 336 },
     { class: 3, ex: 'Một cửa hàng có 6 hộp bút chì như nhau đựng tổng cộng 144 cây bút chì, cửa hàng đã bán hết 4 hộp bút chì. Hỏi cửa hàng còn lại bao nhiêu cây bút chì?', kq: 48 },
     { class: 3, ex: 'Hùng có 56 nghìn đồng mua được 8 quyển truyện, Dũng có ít hơn Hùng 21 nghìn đồng. Hỏi Dũng mua đuợc bao nhiêu quyển truyện tranh ?', kq: 5 },
     { class: 3, ex: 'Lan có 6 hộp kẹo, Lan cho bạn 24 viên kẹo thì Lan còn lại 4 hộp kẹo nguyên. Hỏi ban đầu Lan có tất cả bao nhiêu viên kẹo?', kq: 72 },
     { class: 3, ex: 'Một cửa hàng nhập về 168 bao đường và chia đều vào 3 kho, sau đó lại nhập thêm vào mỗi kho 16 bao đường và bán hết số bao đường trong 2 kho. Hỏi cửa hàng đã bán bao nhiêu bao đường?', kq: 144 },
     { class: 3, ex: 'An có 64 viên bi chia đều thành 8 hộp, Bình có 48 viên bi cũng được chia vào các hộp với số bi có trong mỗi hộp giống như An. Hỏi Bình có ít hơn An bao nhiêu hộp bi?', kq: 2 },
     { class: 3, ex: 'An có 144 viên bi chia đều thành 12 hộp, Bình có 48 viên bi cũng được chia vào các hộp với số bi có trong mỗi hộp giống như An. Hỏi Bình có ít hơn An bao nhiêu hộp bi?', kq: 8 },
     { class: 3, ex: 'An có 81 viên bi chia đều thành 9 hộp, Bình có 63 viên bi cũng được chia vào các hộp với số bi có trong mỗi hộp giống như An. Hỏi Bình có ít hơn An bao nhiêu hộp bi?', kq: 2 },
     { class: 3, ex: 'An có 72 viên bi chia đều thành 8 hộp, Bình có 54 viên bi cũng được chia vào các hộp với số bi có trong mỗi hộp giống như An. Hỏi Bình có ít hơn An bao nhiêu hộp bi?', kq: 3 },
     { class: 3, ex: 'Biết rằng cứ 5 gói kẹo như nhau thì đếm được 40 viên . Hỏi muốn chia cho 36 em thiếu nhi , mỗi em 6 viên kẹo thì phải mua tất cả bao nhiêu gói kẹo ?', kq: 27 },
     { class: 3, ex: 'Biết rằng cứ 8 gói kẹo như nhau thì đếm được 48 viên . Hỏi muốn chia cho 36 em thiếu nhi , mỗi em 12 viên kẹo thì phải mua tất cả bao nhiêu gói kẹo ?', kq: 72 },
     { class: 3, ex: 'Biết rằng cứ 9 gói kẹo như nhau thì đếm được 54 viên . Hỏi muốn chia cho 72 em thiếu nhi , mỗi em 3 viên kẹo thì phải mua tất cả bao nhiêu gói kẹo ?', kq: 36 },
     { class: 3, ex: 'Dũng có 72 viên bi gồm bi xanh và bi đỏ, Dũng chia ra thành các hộp bằng nhau, Dũng chia được 5 hộp bi xanh và 4 hộp bi đỏ. Hỏi Dũng có bao nhiêu viên xanh', kq: 40 },
     { class: 3, ex: 'Dũng có 81 viên bi gồm bi xanh và bi đỏ, Dũng chia ra thành các hộp bằng nhau, Dũng chia được 5 hộp bi xanh và 4 hộp bi đỏ. Hỏi Dũng có bao nhiêu viên đỏ', kq: 36 },
     { class: 3, ex: 'Dũng có 121 viên bi gồm bi xanh và bi đỏ, Dũng chia ra thành các hộp bằng nhau, Dũng chia được 5 hộp bi xanh và 6 hộp bi đỏ. Hỏi Dũng có bao nhiêu viên xanh', kq: 55 },
     { class: 3, ex: 'Dũng có 144 viên bi gồm bi xanh và bi đỏ, Dũng chia ra thành các hộp bằng nhau, Dũng chia được 8 hộp bi xanh và 4 hộp bi đỏ. Hỏi Dũng có bao nhiêu viên đỏ', kq: 48 },
     { class: 3, ex: 'Một cửa hàng có một số thùng dầu như nhau chứa tổng cộng 72 lít , ngời ta thêm vào số dầu đó 3 thùng thì số dầu có tất cả là 99 lít . Hỏi lúc đầu cửa hàng có bao nhiêu thùng dầu?', kq: 8 },
     { class: 3, ex: 'Một cửa hàng có một số thùng dầu như nhau chứa tổng cộng 81 lít , ngời ta thêm vào số dầu đó 3 thùng thì số dầu có tất cả là 108 lít . Hỏi lúc đầu cửa hàng có bao nhiêu thùng dầu?', kq: 9 },
     { class: 3, ex: 'Một cửa hàng có một số thùng dầu như nhau chứa tổng cộng 50 lít , ngời ta thêm vào số dầu đó 3 thùng thì số dầu có tất cả là 80 lít . Hỏi lúc đầu cửa hàng có bao nhiêu thùng dầu?', kq: 5 },
     { class: 3, ex: 'Một cửa hàng có một số thùng dầu như nhau chứa tổng cộng 121 lít , ngời ta thêm vào số dầu đó 3 thùng thì số dầu có tất cả là 154 lít . Hỏi lúc đầu cửa hàng có bao nhiêu thùng dầu?', kq: 11 },

     { class: 3, ex: 'Huệ xếp 9 chiếc thuyền mất 36 phút, Hoa xếp 6 chiếc thuyền mất 30 phút. Hỏi Huệ xếp 6 chiếc thuyền và Hoa xếp 4 chiếc thuyền thì ai xếp xong trước ? (biết 2 bạn bắt đầu xếp thuyền cùng một lúc. (nếu là huệ hãy trả lời 1, nếu là hoa hãy trả lời 2)', kq: 2 },
     { class: 3, ex: 'Huệ xếp 8 chiếc thuyền mất 64 phút, Hoa xếp 6 chiếc thuyền mất 54 phút. Hỏi Huệ xếp 7 chiếc thuyền và Hoa xếp 7 chiếc thuyền thì ai xếp xong trước ? (biết 2 bạn bắt đầu xếp thuyền cùng một lúc. (nếu là huệ hãy trả lời 1, nếu là hoa hãy trả lời 2)', kq: 1 },
     { class: 3, ex: 'Huệ xếp 4 chiếc thuyền mất 36 phút, Hoa xếp 3 chiếc thuyền mất 30 phút. Hỏi Huệ xếp 5 chiếc thuyền và Hoa xếp 4 chiếc thuyền thì ai xếp xong trước ? (biết 2 bạn bắt đầu xếp thuyền cùng một lúc. (nếu là huệ hãy trả lời 1, nếu là hoa hãy trả lời 2)', kq: 2 },
     { class: 3, ex: 'Huệ xếp 5 chiếc thuyền mất 45 phút, Hoa xếp 4 chiếc thuyền mất 32 phút. Hỏi Huệ xếp 6 chiếc thuyền và Hoa xếp 6 chiếc thuyền thì ai xếp xong trước ? (biết 2 bạn bắt đầu xếp thuyền cùng một lúc. (nếu là huệ hãy trả lời 1, nếu là hoa hãy trả lời 2)', kq: 2 },
     { class: 3, ex: 'Có 5 thùng kẹo , mỗi thùng có 6 hộp kẹo, mỗi hộp có 32 viên kẹo. Hỏi có tất cả bao nhiêu viên kẹo?', kq: 960 },
     { class: 3, ex: 'Có 6 thùng kẹo , mỗi thùng có 4 hộp kẹo, mỗi hộp có 33 viên kẹo. Hỏi có tất cả bao nhiêu viên kẹo?', kq: 792 },
     { class: 3, ex: 'Có 3 thùng kẹo , mỗi thùng có 3 hộp kẹo, mỗi hộp có 20 viên kẹo. Hỏi có tất cả bao nhiêu viên kẹo?', kq: 180 },
     { class: 3, ex: 'Có 7 thùng kẹo , mỗi thùng có 8 hộp kẹo, mỗi hộp có 18 viên kẹo. Hỏi có tất cả bao nhiêu viên kẹo?', kq: 1008 },
     { class: 3, ex: 'Có 21 thùng kẹo , mỗi thùng có 5 hộp kẹo, mỗi hộp có 39 viên kẹo. Hỏi có tất cả bao nhiêu viên kẹo?', kq: 4095 },
     { class: 3, ex: 'Có 12 thùng kẹo , mỗi thùng có 9 hộp kẹo, mỗi hộp có 19 viên kẹo. Hỏi có tất cả bao nhiêu viên kẹo?', kq: 2052 },
     { class: 3, ex: 'Có 14 thùng kẹo , mỗi thùng có 11 hộp kẹo, mỗi hộp có 27 viên kẹo. Hỏi có tất cả bao nhiêu viên kẹo?', kq: 4158 },
     { class: 3, ex: 'Có 17 thùng kẹo , mỗi thùng có 10 hộp kẹo, mỗi hộp có 29 viên kẹo. Hỏi có tất cả bao nhiêu viên kẹo?', kq: 4930 },
     { class: 3, ex: 'Có 19 thùng kẹo , mỗi thùng có 4 hộp kẹo, mỗi hộp có 19 viên kẹo. Hỏi có tất cả bao nhiêu viên kẹo?', kq: 1444 },
     { class: 3, ex: 'Có 16 thùng kẹo , mỗi thùng có 8 hộp kẹo, mỗi hộp có 20 viên kẹo. Hỏi có tất cả bao nhiêu viên kẹo?', kq: 2560 },
     { class: 3, ex: 'Có 8 bạn nhỏ đi mua bi, mỗi bạn mua 3 bi xanh và 4 bi đỏ. Hỏi 8 bạn mua tất cả bao nhiêu viên bi?', kq: 56 },
     { class: 3, ex: 'Có 7 bạn nhỏ đi mua bi, mỗi bạn mua 4 bi xanh và 8 bi đỏ. Hỏi 5 bạn mua tất cả bao nhiêu viên bi?', kq: 60 },
     { class: 3, ex: 'Có 12 bạn nhỏ đi mua bi, mỗi bạn mua 6 bi xanh và 4 bi đỏ. Hỏi 8 bạn mua tất cả bao nhiêu viên bi?', kq: 80 },
     { class: 3, ex: 'Có 18 bạn nhỏ đi mua bi, mỗi bạn mua 7 bi xanh và 7 bi đỏ. Hỏi 8 bạn mua tất cả bao nhiêu viên bi?', kq: 112 },
     { class: 3, ex: 'Có 10 bạn nhỏ đi mua bi, mỗi bạn mua 9 bi xanh và 12 bi đỏ. Hỏi 8 bạn mua tất cả bao nhiêu viên bi?', kq: 168 },
     { class: 3, ex: 'Có 9 bạn nhỏ đi mua bi, mỗi bạn mua 8 bi xanh và 9 bi đỏ. Hỏi 8 bạn mua tất cả bao nhiêu viên bi?', kq: 136 },
     //=======================================================================
     { class: 3, ex: 'Có 11 thùng kẹo như nhau chứa tổng cộng 1650 viên kẹo, mỗi thùng kẹo có 6 gói. Hỏi mỗi gói chứa bao nhiêu viên kẹo?', kq: 25 },
     { class: 3, ex: 'Có 18 thùng kẹo như nhau chứa tổng cộng 1512 viên kẹo, mỗi thùng kẹo có 7 gói. Hỏi mỗi gói chứa bao nhiêu viên kẹo?', kq: 12 },
     { class: 3, ex: 'Có 17 thùng kẹo như nhau chứa tổng cộng 1088 viên kẹo, mỗi thùng kẹo có 8 gói. Hỏi mỗi gói chứa bao nhiêu viên kẹo?', kq: 8 },
     { class: 3, ex: 'Có 19 thùng kẹo như nhau chứa tổng cộng 1539 viên kẹo, mỗi thùng kẹo có 9 gói. Hỏi mỗi gói chứa bao nhiêu viên kẹo?', kq: 9 },
     { class: 3, ex: 'Có 21 thùng kẹo như nhau chứa tổng cộng 1050 viên kẹo, mỗi thùng kẹo có 5 gói. Hỏi mỗi gói chứa bao nhiêu viên kẹo?', kq: 10 },
     { class: 3, ex: 'Dũng có 16 viên bi, Toàn có số bi gấp 5 lần số bi của Dũng. Hỏi cả hai bạn có tất cả bao nhiêu viên bi.', kq: 96 },
     { class: 3, ex: 'Dũng có 19 viên bi, Toàn có số bi gấp 6 lần số bi của Dũng. Hỏi cả hai bạn có tất cả bao nhiêu viên bi.', kq: 133 },
     { class: 3, ex: 'Dũng có 21 viên bi, Toàn có số bi gấp 3 lần số bi của Dũng. Hỏi cả hai bạn có tất cả bao nhiêu viên bi.', kq: 84 },
     { class: 3, ex: 'Dũng có 25 viên bi, Toàn có số bi gấp 2 lần số bi của Dũng. Hỏi cả hai bạn có tất cả bao nhiêu viên bi.', kq: 75 },
     { class: 3, ex: 'Một cửa hàng ngày thứ nhất bán được 36 kg đường, ngày thứ hai bán được số đường giảm đi 3 lần so với ngày thứ nhất. Hỏi ngày thứ hai bán ít hơn ngày thứ nhất bao nhiêu ki lô gam đường?', kq: 24 },
     { class: 3, ex: 'Có ba thùng dầu, thùng thứ nhất chứa 16 lít, thùng thứ hai chứa gấp 3 lần thùng thứ nhất, thùng thứ ba chứa kém thùng thứ hai 2 lần. Hỏi thùng thứ ba chứa bao nhiêu lít dầu?', kq: 24 },
     { class: 3, ex: 'Có ba thùng dầu, thùng thứ nhất chứa 18 lít, thùng thứ hai chứa gấp 3 lần thùng thứ nhất, thùng thứ ba chứa kém thùng thứ hai 2 lần. Hỏi thùng thứ ba chứa bao nhiêu lít dầu?', kq: 27 },
     { class: 3, ex: 'Có ba thùng dầu, thùng thứ nhất chứa 24 lít, thùng thứ hai chứa gấp 3 lần thùng thứ nhất, thùng thứ ba chứa kém thùng thứ hai 4 lần. Hỏi thùng thứ ba chứa bao nhiêu lít dầu?', kq: 18 },
     { class: 3, ex: 'Có ba thùng dầu, thùng thứ nhất chứa 25 lít, thùng thứ hai chứa gấp 3 lần thùng thứ nhất, thùng thứ ba chứa kém thùng thứ hai 5 lần. Hỏi thùng thứ ba chứa bao nhiêu lít dầu?', kq: 15 },
     { class: 3, ex: 'Có ba thùng dầu, thùng thứ nhất chứa 30 lít, thùng thứ hai chứa gấp 3 lần thùng thứ nhất, thùng thứ ba chứa kém thùng thứ hai 3 lần. Hỏi thùng thứ ba chứa bao nhiêu lít dầu?', kq: 30 },
     { class: 3, ex: 'Có hai bao gạo, bao thứ nhất đựng 72 kg gạo và đựng gấp 3 lần bao thứ hai. Hỏi bao thứ nhất đựng nhiều hơn bao thứ hai bao nhiêu ki lô gam gạo?', kq: 48 },
     { class: 3, ex: 'Dũng có 72 viên bi gồm bi xanh và bi đỏ, Dũng chia ra thành các hộp bằng nhau, Dũng chia đợc 5 hộp bi xanh và 4 hộp bi đỏ. Hỏi Dũng có bao nhiêu viên xanh?', kq: 45 },
     { class: 3, ex: 'Trong các số: 42078, 42075, 42090, 42100, 42099, 42109, 43000. Số lớn nhất là:', kq: 43000 },
     { class: 3, ex: 'Số liền sau của 78999 là:', kq: 79000 },
     { class: 3, ex: 'Giá trị của biểu thức 2342 + 403 x 6 là:', kq: 4760 },
     { class: 3, ex: '2 giờ = … phút Số thích hợp điền vào chỗ chấm là:', kq: 120 },
     { class: 3, ex: 'Mua 2kg gạo hết 18000 đồng. Vậy mua 5 kg gạo hết số tiền là:', kq: 45000 },
     { class: 3, ex: 'Một miếng bìa hình chữ nhật có chiều dài là 12 cm, chiều rộng bằng 1/3 chiều dài. Chu vi hình chữ nhật đó là:', kq: 32 },
     { class: 3, ex: 'Một ô tô đi trong 8 giờ thì được 32624 km. Hỏi ô tô đó đi trong 3 giờ được bao nhiêu ki – lô – mét?', kq: 12234 },
     { class: 3, ex: 'X x 6 = 3048 : 2', kq: 254 },
     { class: 3, ex: '56 : X = 1326 – 1318', kq: 7 },
     { class: 3, ex: 'Số liền sau của số 39759', kq: 39760 },
     { class: 3, ex: 'Tìm số tròn nghìn ở giữa số 9068 và 11982 là', kq: 10000 },
     { class: 3, ex: '(98725 – 87561) x 3 = .....', kq: 33492 },
     { class: 3, ex: '12356 + 62154 : 9 = ......', kq: 19262 },
     { class: 3, ex: '3km 12m =......m', kq: 3012 },
     { class: 3, ex: '4 giờ 9 phút = ......phút', kq: 249 },
     { class: 3, ex: 'Một đội thuỷ lợi đào được 132 m mương trong 6 ngày . Hỏi đội đó đào được bao nhiêu m mương trong 7 ngày?', kq: 154 },
     { class: 3, ex: '63754 + 25436', kq: 89190 },
     { class: 3, ex: '93507 - 7236 ', kq: 86271 },
     { class: 3, ex: '47264 x 4  ', kq: 189056 },
     { class: 3, ex: '72296 : 7', kq: 10328 },
     { class: 3, ex: 'X + 7839 = 16784', kq: 8945 },
     { class: 3, ex: ' 5 x X = 12475', kq: 2495 },
     { class: 3, ex: 'X : 12457 = 9', kq: 112113 },
     { class: 3, ex: ' (84371 – 45263) : 3 =', kq: 13036 },
     { class: 3, ex: '1608 x 5 : 4', kq: 2010 },
     { class: 3, ex: '12000: (3+5) =', kq: 1500 },
     { class: 3, ex: '(21470 + 34252) : 6 =', kq: 9287 },
     { class: 3, ex: '5000 x (37 - 15) = ', kq: 110000 },
     { class: 3, ex: '65370 - 252 x 2 =', kq: 64866 },
     { class: 3, ex: 'Mẹ đem 100 000 đồng đi chợ; mẹ mua cho Mai một đôi giày hết 36500 đồng và mua một áo phông hết 26500 đồng. Số tiền còn lại mẹ dùng để mua thức ăn. Hỏi mẹ đã dùng bao nhiêu tiền để mua thức ăn?', kq: 37000 },
     { class: 3, ex: '4083 : 4 = 102 (dư 3) Nếu đúng thì ghi số 1 , sai ghi số 0.', kq: 0 },
     { class: 3, ex: '4083 : 4 = 120 (dư 3) Nếu đúng thì ghi số 1 , sai ghi số 0.', kq: 0 },
     { class: 3, ex: '4083 : 4 = 1020 (dư 3) Nếu đúng thì ghi số 1 , sai ghi số 0.', kq: 1 },
     { class: 3, ex: '4083 : 4 = 12 (dư 3) Nếu đúng thì ghi số 1 , sai ghi số 0.', kq: 0 },
     { class: 3, ex: 'Tích của số lớn nhất có 4 chữ số và số bé nhất có 2 chữ số là:', kq: 99990 },
     { class: 3, ex: 'Tìm số x biết "thương của 62680 và x" thì bằng 8', kq: 7835 },
     { class: 3, ex: 'Có 45 kg bột mì đựng đều trong 9 bao. Hỏi 75kg bột mì đựng đều trong mấy bao như thế?', kq: 15 },
     { class: 3, ex: ' Tính chu vi một hình chữ nhật, biết chiều dài là 4m 30cm và chiều rộng là 80cm? (tính theo cm)', kq: 1020 },
     { class: 3, ex: ' Tính chu vi một hình chữ nhật, biết chiều dài là 5m 20cm và chiều rộng là 70cm? (tính theo cm)', kq: 1180 },
     { class: 3, ex: ' Tính chu vi một hình chữ nhật, biết chiều dài là 3m 15cm và chiều rộng là 50cm? (tính theo cm)', kq: 730 },
     { class: 3, ex: ' Tính chu vi một hình chữ nhật, biết chiều dài là 4m 10cm và chiều rộng là 45cm? (tính theo cm)', kq: 910 },
     { class: 3, ex: ' Tính diện tích một hình chữ nhật, biết chiều dài là 3m 25cm và chiều rộng là 80cm? (tính theo cm)', kq: 26000 },
     { class: 3, ex: ' Tính diện tích một hình chữ nhật, biết chiều dài là 6m 30cm và chiều rộng là 65cm? (tính theo cm)', kq: 40950 },
     { class: 3, ex: ' Tính diện tích một hình chữ nhật, biết chiều dài là 6m 15cm và chiều rộng là 70cm? (tính theo cm)', kq: 43050 },
     { class: 3, ex: ' Tính diện tích một hình chữ nhật, biết chiều dài là 3m 45cm và chiều rộng là 85cm? (tính theo cm)', kq: 29325 },
     { class: 3, ex: '3000 x 6 - 5000 =........', kq: 13000 },
     { class: 3, ex: '42000 : 7 + 8000 =.......', kq: 14000 },
     { class: 3, ex: '54000 : 9 + 4000 =.......', kq: 10000 },
     { class: 3, ex: '72000 : 9 + 1000 =.......', kq: 9000 },
     { class: 3, ex: 'Tính diện tích miếng bìa hình vuông, biết hình vuông đó có chu vi là 3dm 2cm.(tính theo cm)', kq: 64 },
     { class: 3, ex: '528 + 216 : 2 x 3', kq: 852 },
     { class: 3, ex: '26946 : (9 x 2)', kq: 1497 },
     { class: 3, ex: '12 x 3 + 216 : 2', kq: 144 },
     { class: 3, ex: '6546 : 2 - (9 x 2)', kq: 3255 },
     { class: 3, ex: 'Trong một xưởng may công nghiệp, cứ 15 m vải thì may được 5 bộ quần áo cùng một cỡ. Hỏi có 330m vải thì may được bao nhiêu bộ quần áo với cùng cỡ đó?', kq: 110 },
     { class: 3, ex: '100 + 100 : 4 - 50 : 2', kq: 100 },
     { class: 3, ex: '(6x8 – 48): (10 +11 +12 +13 +14)', kq: 0 },
     { class: 3, ex: '10000 x 2 + 60000', kq: 80000 },
     { class: 3, ex: '(7000 – 3000) x 2', kq: 8000 },
     { class: 3, ex: 'Túi thứ nhất đựng 18kg gạo, gấp 3 lần túi thứ hai. Hỏi phải lấy ở túi thứ nhất bao nhiêu kg gạo đổ sang túi thứ hai để số gạo ở hai túi bằng nhau?', kq: 6 },
     { class: 3, ex: 'Tính chu vi hình tứ giác ABCD, biết cạnh AB =16cm, BC = 20cm, cạnh CD bằng nửa tổng AB và BC. Cạnh AD gấp đôi hiệu của BC và CD.', kq: 58 },
     { class: 3, ex: 'Tính chu vi hình tứ giác ABCD, biết cạnh AB =21cm, BC = 11cm, cạnh CD bằng nửa tổng AB và BC. Cạnh AD gấp đôi hiệu của BC và AB.', kq: 68 },
     { class: 3, ex: 'Tính chu vi hình tứ giác ABCD, biết cạnh AB =22cm, BC = 10cm, cạnh CD bằng nửa hiệu AB và BC. Cạnh AD gấp đôi hiệu của BC và AB.', kq: 62 },
     { class: 3, ex: 'Tính chu vi hình tứ giác ABCD, biết cạnh AB =33cm, BC = 13cm, cạnh CD bằng nửa tổng AB và BC. Cạnh AD gấp đôi hiệu của AB và CD.', kq: 89 },
     { class: 3, ex: 'Tính chu vi hình tứ giác ABCD, biết cạnh AB =32cm, BC = 18cm, cạnh CD bằng nửa tổng AB và BC. Cạnh AD gấp đôi hiệu của BC và CD.', kq: 89 },
     { class: 3, ex: '125 - 25 x 3', kq: 50 },
     { class: 3, ex: '125 : 5 + 75 : 5', kq: 10 },
     { class: 3, ex: '30 : 3 + 7 x 8', kq: 66 },
     { class: 3, ex: 'Lớp 3 A có 40 học sinh được chia thành 4 tổ, mỗi tổ lại chia đều thành 2 nhóm. Hỏi mỗi nhóm có bao nhiêu học sinh?', kq: 5 },
     { class: 3, ex: '2m 5dm =......dm', kq: 25 },
     { class: 3, ex: '2km 500m =......m', kq: 2500 },
     { class: 3, ex: '2m 5cm=..... cm  ', kq: 205 },
     { class: 3, ex: '2km 50m =.....m', kq: 2050 },
     { class: 3, ex: 'X x 8 = 2864', kq: 358 },
     { class: 3, ex: 'X : 5 = 4242', kq: 21210 },
     { class: 3, ex: 'X + 3438 = 25434', kq: 21996 },
     { class: 3, ex: 'X - 5875 = 57667', kq: 63542 },
     { class: 3, ex: 'X : 8 = 4142', kq: 33136 },
     { class: 3, ex: 'X : 5 = 8760', kq: 43800 },
     { class: 3, ex: 'X - 6658 = 99764', kq: 106422 },
     { class: 3, ex: 'X + 6755 = 78992', kq: 72237 },
     { class: 3, ex: 'X : 7 = 7554', kq: 52878 },
     { class: 3, ex: 'X : 4 = 3747', kq: 14988 },
     { class: 3, ex: 'X : 3 = 1124', kq: 3372 },
     { class: 3, ex: 'X - 4564 = 4676', kq: 9240 },
     { class: 3, ex: '9454 - X = 3564', kq: 5890 },
     { class: 3, ex: '5743 + X = 9242', kq: 3499 },
     { class: 3, ex: '2 x X = 4440', kq: 2220 },
     { class: 3, ex: 'X : 5 = 550', kq: 2750 },
     { class: 3, ex: 'X x 2 = 2864', kq: 1432 },
     { class: 3, ex: 'X : 4 = 4212', kq: 16848 },
     { class: 3, ex: 'X + 5548 = 25434', kq: 19886 },
     { class: 3, ex: 'X - 5115 = 5761', kq: 10876 },
     { class: 3, ex: 'X : 3 = 4142', kq: 12426 },
     { class: 3, ex: 'X : 5 = 8100', kq: 40500 },
     { class: 3, ex: 'X - 948 = 91111', kq: 92059 },
     { class: 3, ex: 'X + 615 = 7634', kq: 7017 },
     { class: 3, ex: 'X : 7 = 1112', kq: 7784 },
     { class: 3, ex: 'X : 4 = 4247', kq: 16988 },
     { class: 3, ex: 'X x 3 = 9663', kq: 3221 },
     { class: 3, ex: 'X - 4454 = 1426', kq: 5880 },
     { class: 3, ex: '423 x 2', kq: 846 },
     { class: 3, ex: '243 x 3 ', kq: 729 },
     { class: 3, ex: '231 x 4', kq: 924 },
     { class: 3, ex: '933 : 3', kq: 311 },
     { class: 3, ex: '312 : 8', kq: 39 },
     { class: 3, ex: '4268 + 3917', kq: 8185 },
     { class: 3, ex: '3845 + 2625', kq: 6470 },
     { class: 3, ex: '7331 – 759', kq: 6572 },
     { class: 3, ex: '2457 : 3', kq: 819 },
     { class: 3, ex: '1414 x 5', kq: 7070 },
     { class: 3, ex: '1736 – 456', kq: 1280 },
     { class: 3, ex: '1204 : 4', kq: 301 },
     { class: 3, ex: '15 : x = 24 : 8', kq: 5 },
     { class: 3, ex: '42 : x = 36 : 6 ', kq: 7 },
     { class: 3, ex: '84 : x = 18 : 9', kq: 42 },
     { class: 3, ex: 'Thùng thứ nhất có 16 lít dầu, thùng thứ nhất có số dầu bằng 1/8 số dầu thùng thứ hai. Hỏi thùng thứ hai có bao nhiêu lít dầu?', kq: 128 },
     { class: 3, ex: 'Có 234 kg gạo chia đều vào 9 túi. Hỏi mỗi túi có bao nhiêu kg gạo?', kq: 26 },
     { class: 3, ex: 'Chị An năm nay 16 tuổi, tuổi của bố chị An gấp 3 lần tuổi của chị An. Hỏi hai bố con chị An năm nay bao nhiêu tuổi ?', kq: 48 },
     { class: 3, ex: 'Tính nhanh : 236 + 372 + 453 - 253 - 172 - 36', kq: 600 },
     { class: 3, ex: '612 - 342 : 9 + (102 – 68)', kq: 608 },
     { class: 3, ex: 'Lan có 56 que tính, Lan chia cho Hồng 1/4 số que tính đó, chia cho Huệ 1/3 số que tính còn lại. Hỏi sau khi chia cho 2 bạn Lan còn lại bao nhiêu que tính?', kq: 28 },
     { class: 3, ex: ' Một đám ruộng hình chữ nhật có chiều dài gấp 3 lần chiều rộng. Tính diện tích đám ruộng đó biết chu vi đám ruộng đó là 48 m', kq: 128 },
     { class: 3, ex: 'Dũng có 12 viên phấn, Toàn có số viên phấn gấp 3 lần số viên phấn của Dũng. Hỏi hai bạn có tất cả bao nhiêu viên phấn?', kq: 48 },
     { class: 3, ex: ' Một cửa hàng ngày thứ nhất bán được 36kg đường, ngày thứ hai bán được số đường giảm đi 3 lần so với ngày thứ nhất. Hỏi ngày thứ hai bán ít hơn ngày thứ nhất bao nhiêu ki-lô-gam đường?', kq: 24 },
     { class: 3, ex: 'Có ba thùng dầu, thùng thứ nhát chứa 16lít, thùng thứ hai chứa gấp 3 lần thùng thứ nhất, thùng thứ ba chứa kém thùng thứ hai 2 lần. Hỏi thùng thứ ba chứa bao nhiêu lít dầu?', kq: 24 },
     { class: 3, ex: 'Có hai bao gạo, bao thứ nhất đựng 72kg gạo và đựng gấp ba lần bao thứ hai. Hỏi bao thứ nhất đựng nhiều hơn bao thứ hai bao nhiêu ki-lô-gam gạo?', kq: 48 },
     { class: 3, ex: 'Có hai tổ công nhân, tổ một có 15 công nhân, tổ hai nếu có thêm 6 công nhân thì sẽ gấp đôi tổ một. Hỏi hai tổ có bao nhiêu công nhân?', kq: 39 },
     { class: 3, ex: 'An đi thăm một nông trại có nuôi gà và heo, An đếm được 216 chân gà và thấy só gà gấp 3 lần số heo. Hỏi nông trại có bao nhiêu con heo?', kq: 18 },
     { class: 3, ex: 'Ba và Đức có tất cả 48 viên bi, biết số bi của Đức gấp 3 lần số bi của Ba. Hỏi Đức có nhiều hơn Ba bao nhiêu viên bi?', kq: 24 },
     { class: 3, ex: 'Thùng thứ nhất có 8 lít dầu, thùng thứ hai có nhiều hơn thùng thứ nhất 32 lít dầu. Hỏi thùng thứ hai có số lít dầu gấp mấy lần số lít dầu của thùng thứ nhất?', kq: 5 },
     { class: 3, ex: 'Tổng của 47856 và 35687 là', kq: 83543 },
     { class: 3, ex: 'Mai có 7 viên bi, Hồng có 15 viên bi. Hỏi Hồng phải cho Mai bao nhiêu viên bi để số bi của hai bạn bằng nhau. ', kq: 4 },
     { class: 3, ex: '9m 4cm= … cm ', kq: 904 },
     { class: 3, ex: 'AB = 5cm, BD= 13cm. Diện tích hình chữ nhật ABDC là', kq: 65 },
     { class: 3, ex: '4m 4 dm = ................... cm', kq: 440 },
     { class: 3, ex: 'Một người đi bộ trong 6 phút đi được 480 m. Hỏi trong 9 phút người đó đi được bao nhiêu m đường (Quãng đường trong mỗi phút đi đều như nhau)? ', kq: 720 },
     { class: 3, ex: 'Tìm x biết: 8462 -  x = 762  ', kq: 7700 },
     { class: 3, ex: 'Số nhỏ nhất có 4 chữ số là', kq: 1000 },
     { class: 3, ex: 'Số lẻ liền sau số 2007 là: ', kq: 2009 },
     { class: 3, ex: 'Nhà em có 24 con gà. Số vịt nhiều hơn số gà là 2 con. Hỏi nhà em có bao nhiêu con vịt? ', kq: 26 },
     { class: 3, ex: 'Mẹ sinh con khi mẹ 25 tuổi. Hỏi khi con lên 9 tuổi thì mẹ bao nhiêu tuổi ', kq: 34 },
     { class: 3, ex: 'Hiệu của số lớn nhất có bốn chữ số và số nhỏ nhất có ba chữ số là', kq: 9899 },
     { class: 3, ex: 'Lớp trưởng chỉ huy cả lớp xếp hàng. Cả lớp xếp được 4 hàng, mỗi hàng có 7 bạn. Hỏi lớp đó có bao nhiêu học sinh? ', kq: 29 },
     { class: 3, ex: 'Tìm một số biết rằng lấy số đó trừ đi 34 thì bằng 43 cộng với 58? Số cần tìm là: ', kq: 135 },
     { class: 3, ex: 'Tôi nghĩ ra một số, nếu thêm vào số tôi nghĩ 72 đơn vị thì được 1 số mới, nếu bớt số mới đi 27 đơn vị thì được kết quả là 81. Đố bạn biết số tôi nghĩ là số nào?', kq: 36 },
     { class: 3, ex: 'Tính giá trị của biểu thức:4536 + 73 845 : 9 ', kq: 12741 },
     { class: 3, ex: 'Bể thứ nhất chứa được 4 827 lít nước. Bể thứ hai chứa được 2 634 lít nước. Cả hai bể chứa là:  ', kq: 7461 },
     { class: 3, ex: 'Một hình vuông có số đo cạnh là 24 cm. Chu vi hình vuông đó là', kq: 96 },
     { class: 3, ex: 'Lớp 3A có 28 học sinh. Nếu số học sinh lớp 3A xếp đều vào 7 hàng thì lớp 3B có 6 hàng như thế. Hỏi lớp 3B có bao nhiêu học sinh? ', kq: 24 },
     { class: 3, ex: 'Nếu lấy số lớn nhất có 4 chữ số khác nhau trừ đi số chẵn nhỏ nhất có 4 chữ số giống nhau thì được hiệu là: ', kq: 7654 },
     { class: 3, ex: 'Tổng của số lớn nhất có 4 chữ số với số bé nhất có 4 chữ số khác nhau là: ', kq: 11022 },
     { class: 3, ex: '. Tìm số trừ biết số bị trừ là 45 và hiệu là 18? Số trừ là: ', kq: 27 },
     { class: 3, ex: 'Có 2 nguồn sách. Nguồn thứ nhất có 9 cuốn sách, nguồn thứ 2 nếu có thêm 3 cuốn sách thì sẽ gấp đôi số sách nguồn thứ nhất. Hỏi cả 2 nguồn có bao nhiêu cuốn sách. ', kq: 24 },
     { class: 3, ex: 'Số chẵn lớn nhất có 5 chữ số là: ', kq: 99998 },
     { class: 3, ex: 'Có 372 quyển sách xếp đều vào 2 tủ, mỗi tủ có 3 ngăn. Hỏi mỗi ngăn có bao nhiêu quyển sách? Biết mỗi ngăn có số sách như nhau. ', kq: 62 },
     { class: 3, ex: 'Nếu lấy số chẵn lớn nhất có 5 chữ số trừ đi số lẻ bé nhất có 4 chữ số thì được hiệu là: ', kq: 98997 },
     { class: 3, ex: 'Kết quả của biểu thức: 24 + 36 x 8 là ', kq: 312 },
     { class: 3, ex: 'Diện tích một hình vuông là 9 cm2. Hỏi chu vi hình vuông đó là bao nhiêu? ', kq: 12 },
     { class: 3, ex: 'Một sợi dây đồng dài 36 dam được cắt ra thành 2 đoạn, đoạn thứ nhất dài 15 dam. Đoạn thứ hai dài là:  ', kq: 21 },
     { class: 3, ex: 'Em có một số kẹo, em cho bạn 1/3 số kẹo, em ăn 3 cái thì còn lại đúng 3 cái. Hỏi lúc đầu em có bao nhiêu cái kẹo? ', kq: 9 },
     { class: 3, ex: 'Số nào khi nhân với 7 thì được kết quả là số lớn nhất có 2 chữ số khác nhau? ', kq: 14 },
     { class: 3, ex: 'Một kilôgam táo giá 6000 đồng. Để mua được 3kg táo cần phải trả bao nhiêu tiền?', kq: 18000 },
     { class: 3, ex: '3km 6dm = … m. Số cần điền vào chỗ chấm là: ', kq: 3060 },
     { class: 3, ex: 'Một gia đình nuôi 100 con gà, ngan và vịt. Trong đó có 21 con gà. Số vịt nhiều gấp 3 lần số gà, còn lại là ngan. Hỏi gia đình đó nuôi bao nhiêu con ngan? ', kq: 16 },
     { class: 3, ex: 'Đoan thẳng AB dài 100 cm. M là trung điểm của đoạn AB, còn N là trung điểm của đoạn AM. Đoạn thẳng MN có độ dài là: ', kq: 25 },
     { class: 3, ex: 'Tìm x biết:    2002  :  x   =    7            ', kq: 286 },
     { class: 3, ex: 'Số lớn nhất trong các số: 85732;  85723;  78523;  78352 là:', kq: 85732 },
     { class: 3, ex: 'Có 3 hộp bánh, mỗi hộp có 4 gói bánh, mỗi gói có 6 cái bánh. Hỏi tất cả có bao nhiêu cái bánh? ', kq: 72 },
     { class: 3, ex: '. Số lẻ bé nhất có 5 chữ số khác nhau là: ', kq: 1035 },
     { class: 3, ex: 'Tìm số dư của phép chia:  29 : 6  ', kq: 5 },
     { class: 3, ex: 'Bạn 1 làm xong bài Toán về nhà trong 17 phút. Bạn 2 làm xong bài Toán đó trong 1/3 giờ. Bạn 3 làm xong bài Toán đó trong 1/4 giờ. Bạn 4 làm xong bài Toán đó trong 19 phút. Hỏi ai làm nhanh nhất? (1,2,3,4) ', kq: 3 },
     { class: 3, ex: 'Một giờ gấp 5 phút số lần là: ', kq: 12 },
     { class: 3, ex: '. Tìm một số biết rằng lấy số đó cộng với 45 thì bằng 100 trừ đi 27? Số cần tìm là: ', kq: 28 },
     { class: 3, ex: 'Ngăn trên có 9 cuốn sách, ngăn dưới có 12 cuốn sách. Hỏi phải chuyển từ ngăn trên xuống ngăn dưới bao nhiêu cuốn sách để số sách ở ngăn dưới gấp đôi số sách ở ngăn trên', kq: 2 },
     { class: 3, ex: 'Thùng thứ nhất đựng 78 lít sữa. Thùng thứ 2 đựng ít hơn thùng thứ nhất 9 lít nhưng nhiều hơn thùng thứ ba 7 lít. Hỏi cả ba thùng đựng bao nhiêu lít sữa? ', kq: 209 },
     { class: 3, ex: 'Thùng thứ nhất đựng 107 lít sữa. Thùng thứ 2 đựng ít hơn thùng thứ nhất 12 lít nhưng nhiều hơn thùng thứ ba 17 lít. Hỏi cả ba thùng đựng bao nhiêu lít sữa? ', kq: 280 },
     { class: 3, ex: 'Thùng thứ nhất đựng 96 lít sữa. Thùng thứ 2 đựng ít hơn thùng thứ nhất 19 lít nhưng nhiều hơn thùng thứ ba 27 lít. Hỏi cả ba thùng đựng bao nhiêu lít sữa? ', kq: 223 },
     { class: 3, ex: 'Thùng thứ nhất đựng 56 lít sữa. Thùng thứ 2 đựng ít hơn thùng thứ nhất 29 lít nhưng nhiều hơn thùng thứ ba 21 lít. Hỏi cả ba thùng đựng bao nhiêu lít sữa? ', kq: 89 },
     { class: 3, ex: 'Thùng thứ nhất đựng 192 lít sữa. Thùng thứ 2 đựng ít hơn thùng thứ nhất 39 lít nhưng nhiều hơn thùng thứ ba 14 lít. Hỏi cả ba thùng đựng bao nhiêu lít sữa? ', kq: 484 },
     { class: 3, ex: 'Có bao nhiêu số có 2 chữ số mà chữ số hàng chục là 7', kq: 10 },
     { class: 3, ex: 'Một số khi chia cho 6 thì được thương là 8. Hỏi số đó đem chia cho 4 thì được thương là bao nhiêu', kq: 12 },
     { class: 3, ex: 'Một số khi chia cho 3 thì được thương là 9. Hỏi số đó đem chia cho 9 thì được thương là bao nhiêu', kq: 3 },
     { class: 3, ex: 'Một số khi chia cho 8 thì được thương là 8. Hỏi số đó đem chia cho 4 thì được thương là bao nhiêu', kq: 16 },
     { class: 3, ex: '3km 12m = ..... m    ', kq: 3012 },
     { class: 3, ex: 'Tìm x, biết:  182 : x = 7  ', kq: 26 },
     { class: 3, ex: 'Một gia đình nuôi thỏ nhốt đều số thỏ nuôi vào 5 chuồng. Em đếm số thỏ trong 2 chuồng thì được 10 con. Hỏi gia đình đó nuôi bao nhiêu con thỏ? ', kq: 25 },
     { class: 3, ex: 'Chị em năm nay 15 tuổi, 3 năm trước tuổi em bằng 1/2 tuổi chị. Hỏi năm nay em bao nhiêu tuổi? ', kq: 9 },
     { class: 3, ex: 'Số chẵn liền trước của số 99 000 là: ', kq: 98998 },
     { class: 3, ex: 'Trong phép chia một số tự nhiên bất kì cho 3. Số dư lớn nhất có thể có là:', kq: 2 },
     { class: 3, ex: 'Trong phép chia một số tự nhiên bất kì cho 4. Số dư lớn nhất có thể có là:', kq: 3 },
     { class: 3, ex: 'Trong phép chia một số tự nhiên bất kì cho 5. Số dư lớn nhất có thể có là:', kq: 4 },
     { class: 3, ex: 'Trong phép chia một số tự nhiên bất kì cho 6. Số dư lớn nhất có thể có là:', kq: 5 },
     { class: 3, ex: 'Trong phép chia một số tự nhiên bất kì cho 7. Số dư lớn nhất có thể có là:', kq: 6 },
     { class: 3, ex: 'Trong phép chia một số tự nhiên bất kì cho 8. Số dư lớn nhất có thể có là:', kq: 7 },
     { class: 3, ex: 'Trong phép chia một số tự nhiên bất kì cho 9. Số dư lớn nhất có thể có là:', kq: 8 },
     { class: 3, ex: 'Ngày thứ nhất bán được 2358 kg gạo, ngày thứ hai bán được gấp 3 lần ngày thứ nhất. Ngày thứ hai bán được số kg gạo là:  ', kq: 7074 },
     { class: 3, ex: 'Có 45 kg bột mì đựng đều trong 9 bao. Hỏi 75 kg bột mì đựng trong mấy bao? ', kq: 15 },
     { class: 3, ex: 'Mỗi bông hoa có giá tiền là 1.500 đồng. Vậy để mua 10 bông hoa, cần trả bao nhiêu tiền? ', kq: 15000 },
     { class: 3, ex: 'Một miếng bìa hình chữ nhật có chiều dài là 12 cm, chiều rộng bằng 1/3 chiều dài. Chu vi hình chữ nhật đó là:', kq: 32 },
     { class: 3, ex: 'Tuổi mẹ kém tuổi bố 4 tuổi. Tuổi bố gấp 4 lần tuổi con. Năm ngoái mẹ 31 tuổi. Hỏi năm nay con bao nhiêu tuổi? ', kq: 9 },
     { class: 3, ex: 'Học có nhiều hơn Giỏi 18 viên bi. Hỏi Học phải cho Giỏi bao nhiêu viên bi để số bi của 2 bạn bằng nhau? ', kq: 9 },
     { class: 3, ex: 'Muốn may 3 bộ quần áo thì cần 12 m vải. Hỏi nếu may 5 bộ quần áo như thế thì cần bao nhiêu mét vải? ', kq: 20 },
     { class: 3, ex: 'Khi mẹ sinh con thì mẹ 24 tuổi và bố 27 tuổi. Hỏi khi con lên 9 tuổi thì tuổi bố gấp mấy lần tuổi con ', kq: 4 },
     { class: 3, ex: 'Tấm vải thứ nhất dài 154 m, tấm vải thứ hai dài gấp 3 lần tấm vải thứ nhất. Hái cả hai tấm vải dài bao nhiêu mét. ', kq: 616 },
     { class: 3, ex: 'x + 1955 = 6123.   x = ? ', kq: 4168 },
     { class: 3, ex: 'Có bao nhiêu số có 2 chữ số mà chữ số hàng chục là 9: ', kq: 10 },
     { class: 3, ex: 'Có bao nhiêu số có 2 chữ số mà chữ số hàng chục là 5: ', kq: 10 },
     { class: 3, ex: 'Có bao nhiêu số có 2 chữ số mà chữ số hàng chục là 6: ', kq: 10 },
     { class: 3, ex: 'Có bao nhiêu số có 2 chữ số mà chữ số hàng chục là 7: ', kq: 10 },
     { class: 3, ex: 'Có bao nhiêu số có 2 chữ số mà chữ số hàng chục là 8: ', kq: 10 },
     { class: 3, ex: 'Có bao nhiêu số có 2 chữ số mà chữ số hàng chục là 9: ', kq: 10 },
     { class: 3, ex: 'Có bao nhiêu số có 2 chữ số mà chữ số hàng chục là 2: ', kq: 10 },
     { class: 3, ex: 'Có bao nhiêu số có 2 chữ số mà chữ số hàng chục là 1: ', kq: 10 },
     { class: 3, ex: 'Số chẵn lớn nhất có 5 chữ số khác nhau là: ', kq: 98764 },
     { class: 3, ex: 'x - 57932 = 11293       x = ? ', kq: 69225 },
     { class: 3, ex: 'Số thích hợp để điền vào chỗ chấm trong dãy: 1, 5, 9, 13, … là: ', kq: 17 },
     { class: 3, ex: 'Số thích hợp để điền vào chỗ chấm trong dãy: 0, 2, 4, 6, … là: ', kq: 8 },
     { class: 3, ex: 'Số thích hợp để điền vào chỗ chấm trong dãy: 1, 3, 5, 7, … là: ', kq: 9 },
     { class: 3, ex: 'Số thích hợp để điền vào chỗ chấm trong dãy: 1, 11, 21, 31, … là: ', kq: 41 },
     { class: 3, ex: 'Số thích hợp để điền vào chỗ chấm trong dãy: 3, 6, 9, 12, … là: ', kq: 15 },
     { class: 3, ex: 'Số thích hợp để điền vào chỗ chấm trong dãy: 4, 8, 12, 16, … là: ', kq: 20 },
     { class: 3, ex: 'Số thích hợp để điền vào chỗ chấm trong dãy: 5, 10, 15, 20, … là: ', kq: 25 },
     { class: 3, ex: 'Số thích hợp để điền vào chỗ chấm trong dãy: 7, 10, 13, 16, … là: ', kq: 19 },
     { class: 3, ex: 'Số thích hợp để điền vào chỗ chấm trong dãy: 8, 14, 20, 26, … là: ', kq: 32 },
     { class: 3, ex: 'Số thích hợp để điền vào chỗ chấm trong dãy: 11, 22, 33, 44, … là: ', kq: 55 },
     { class: 3, ex: 'Tổng các chữ số của số 57906 là: ', kq: 27 },
     { class: 3, ex: 'Phép chia:   36 573  :  9  có số dư là: ', kq: 6 },
     { class: 3, ex: '3dm 5cm = … mm  Số thích hợp để điền vào chỗ chấm là: ', kq: 350 },
     { class: 3, ex: 'Số gồm 5 chục nghìn, 5 trăm và 5 chục viết là: ', kq: 50550 },
     { class: 3, ex: 'Tôi mua 6 cái bút mỗi cái giá 4 000 đồng và 4 quyển vở mỗi quyển giá 3 000 đồng. Tôi đưa cho người bán hàng tờ tiền 50 000 đồng. Người bán hàng phải trả lại tôi số tiền là: ', kq: 14000 },
     { class: 3, ex: 'Khi mẹ sinh con thì mẹ 24 tuổi và bố 27 tuổi. Hỏi khi con lên 10 tuổi thì tổng số tuổi của cả bố, mẹ và con là bao nhiêu?  ', kq: 81 },
     { class: 3, ex: '. 4m 4 cm = ......... cm ', kq: 404 },
     { class: 3, ex: 'Một số khi chia cho 8 thì có số dư là 5. Hỏi số đó đem chia cho 4 sẽ có số dư là bao nhiêu? ', kq: 1 },
     { class: 3, ex: 'Một số khi chia cho 9 thì có số dư là 6. Hỏi số đó đem chia cho 3 sẽ có số dư là bao nhiêu? ', kq: 0 },
     { class: 3, ex: 'Một số khi chia cho 6 thì có số dư là 5. Hỏi số đó đem chia cho 3 sẽ có số dư là bao nhiêu? ', kq: 2 },
     { class: 3, ex: 'Một số khi chia cho 6 thì có số dư là 2. Hỏi số đó đem chia cho 3 sẽ có số dư là bao nhiêu? ', kq: 2 },
     { class: 3, ex: 'Một hình vuông có cạnh là 8 m. Chu vi của hình vuông đó là:  ', kq: 32 },
     { class: 3, ex: 'Biết AB = 60mm. Diện tích  hình vuông ABDC là (Tính theo mm)', kq: 3600 },
     { class: 3, ex: 'Năm nay mẹ em 36 tuổi, tuổi em ít hơn 1/3 tuổi mẹ là 3 tuổi. Hỏi năm nay em bao nhiêu tuổi? ', kq: 9 },
     { class: 3, ex: 'Khối lớp 3 có 123 học sinh. Khối lớp 4 có nhiều hơn khối lớp 3 là 34 học sinh nhưng ít hơn khối lớp 5 là 45 bạn. Hỏi cả 3 khối có bao nhiêu học sinh? ', kq: 482 },
     { class: 3, ex: 'Khối lớp 7 có 173 học sinh. Khối lớp 8 có ít hơn khối lớp 7 là 64 học sinh nhưng nhiều hơn khối lớp 9 là 35 bạn. Hỏi cả 3 khối có bao nhiêu học sinh? ', kq: 356 },
     { class: 3, ex: 'Khối lớp 2 có 193 học sinh. Khối lớp 3 có nhiều hơn khối lớp 2 là 54 học sinh nhưng ít hơn khối lớp 4 là 55 bạn. Hỏi cả 3 khối có bao nhiêu học sinh? ', kq: 742 },
     { class: 3, ex: '72 : ( 2 x 4 ) = ?  ', kq: 9 },
     { class: 3, ex: 'Một lớp học có 28 học sinh xếp đều vào 4 hàng. Hỏi 3 hàng có bao nhiêu học sinh. ', kq: 21 },
     { class: 3, ex: 'Có bao nhiêu số có 3 chữ số giống nhau: ', kq: 9 },
     { class: 3, ex: 'Trong các số sau, số nào khác với các số còn lại:34657,34567,34675,34756 ', kq: 34756 },
     { class: 3, ex: 'Số gồm 12 nghìn, 12 trăm, mười hai đơn vị viết là: ', kq: 121212 },
     { class: 3, ex: 'Mẹ mua cho Linh một chiếc mũ giá 10.000 đồng và một chiếc khăn giá 25.000 đồng. Mẹ đưa cho cô bán hàng 50.000 đồng. Cô bán hàng phải trả lại mẹ số tiền là: ', kq: 15000 },
     { class: 3, ex: 'Tay phải tôi cầm 1 số viên bi, tay trái tôi cầm 4 viên bi. Nếu thêm vào tay phải của tôi 3 viên bi nữa thì cả 2 tay tôi có 12 viên bi. Vậy số bi lúc đầu ở tay phải của tôi là bao nhiêu? ', kq: 5 },
     { class: 3, ex: '. Số chẵn liền trước số 2346 là: ', kq: 2344 },
     { class: 3, ex: 'Mẹ sinh con khi mẹ 27 tuổi. Hỏi khi tuổi con bằng tuổi mẹ thì tuổi mẹ gấp mấy lần tuổi con ', kq: 2 },
     { class: 3, ex: 'Nhà em có 36 con gà, sau khi bán đi 1/4 số gà đó, số con gà nhà em còn lại là:  ', kq: 27 },
     { class: 3, ex: 'Một hình chữ nhật có chiều dài là 36cm và chiều rộng bằng 1/4 chiều dài. Tính diện tích hình chữ nhật đó. ', kq: 324 },
     { class: 3, ex: 'Có bao nhiêu số chẵn có 2 chữ số mà chữ số hàng đơn vị là 7: ', kq: 0 },
     { class: 3, ex: 'Có bao nhiêu số chẵn có 2 chữ số mà chữ số hàng đơn vị là 9: ', kq: 0 },
     { class: 3, ex: 'Có bao nhiêu số lẻ có 2 chữ số mà chữ số hàng đơn vị là 8: ', kq: 0 },
     { class: 3, ex: 'Có bao nhiêu số chẵn có 2 chữ số mà chữ số hàng đơn vị là 4: ', kq: 9 },
     { class: 3, ex: 'Có 54 học sinh xếp thành 6 hàng đều nhau. Hỏi có 72 học sinh thì xếp thành bao nhiêu hàng như thề', kq: 8 },
     { class: 3, ex: 'Đoạn thẳng AB dài 45 cm, đoạn thẳng CD dài hơn 1/9 đoạn thẳng AB là 5 cm. Hỏi cả 2 đoạn dài bao nhiêu xăng ti mét? ', kq: 55 },
     { class: 3, ex: 'Mỗi giờ có 60 phút thì 1/4 giờ có  ', kq: 15 },
     { class: 3, ex: 'Có 27 lít mật ong đổ đầy vào 9 can. Hỏi nếu có 63 lít mật thì đổ đầy bao nhiêu cái can?', kq: 21 },
     { class: 3, ex: 'Mẹ mua 12 quả cam. Mẹ biếu bà 3 quả, mẹ để phần bố 1/3 số cam còn lại. Số còn lại mẹ chia đều cho 2 anh em. Hỏi 2 anh em mỗi người được bao nhiêu quả cam', kq: 3 },
     { class: 3, ex: 'Anh có 7 nhãn vở, em có 5 nhãn vở. Hỏi anh phải cho em  bao nhiêu nhãn vở để số nhãn vở của anh bằng 1 nửa số nhãn vở của em? ', kq: 3 },
     { class: 3, ex: 'Em có 12 viên bi, em cho bạn An 1/3 số viên bi và cho bạn Bình 3 viên. Hỏi em còn lại bao nhiêu viên bi? ', kq: 5 },
     { class: 3, ex: 'X - 5732 = 1293.        X = ? ', kq: 7025 },
     { class: 3, ex: 'Một số khi chia cho 6 thì được thương là 5 và còn dư 4. Số đó là? ', kq: 34 },
     { class: 3, ex: '6 bao gạo thì đựng được 54 kg gạo. Hỏi 90 kg gạo thì phải đựng trong mấy bao gạo như thế: ', kq: 10 },
     { class: 3, ex: 'Tìm một số biết rằng số đó nhân với 7 thì bằng 72 trừ đi 9. Số đó là: ', kq: 9 },
     { class: 3, ex: '253 + 10 x 4 =  ?  ', kq: 293 },
     { class: 3, ex: 'Một hình vuông có chu vi 40cm. Diện tích hình vuông đó là: ', kq: 100 },
     { class: 3, ex: 'Năm 2007 chị 10 tuổi, em 6 tuổi. Hỏi vào năm nào trước đây thì tuổi chị gấp đôi tuổi em ', kq: 2005 },
     { class: 3, ex: 'Mẹ chia 15 cái kẹo cho 2 anh em, em được nhiều hơn anh 3 cái. Hỏi em được bao nhiêu cái kẹo?', kq: 9 },
     { class: 3, ex: 'Một hình vuông có chu vi 12cm. Tính diện tích hình vuông đó.', kq: 9 },
     { class: 3, ex: '8 hộp bút chì như nhau có 96 cái bút chì. Hỏi 6 hộp như thế có bao nhiêu cái bút chì? ', kq: 72 },
     { class: 3, ex: '. Một xe ô tô trong 4 giờ đi được 240 km. Hỏi trong 6 giờ ô tô đi được bao nhiêu kilômét? ', kq: 360 },
     { class: 3, ex: 'Một hình vuông có chu vi là 20 cm. Diện tích hình vuông đó là: ', kq: 25 },
     { class: 3, ex: '. Năm nay anh 14 tuổi. Tuổi em nhiều hơn một nửa tuổi anh là 2 tuổi. Hỏi trước đây mấy năm tuổi anh gấp đôi tuổi em? ', kq: 4 },
     { class: 3, ex: 'Rút gọn phân số sau 24/46', kq: 12 },
     { class: 3, ex: 'Rút gọn phân số sau 4/5', kq: 4 },
     { class: 3, ex: 'Phân số 14/3 đã rút gọn chưa, nếu rồi hãy trả lời 1, nếu chữa hãy trả lời 2', kq: 1 },
     { class: 3, ex: 'Rút gọn phân số sau : 7/49', kq: 1 },
     { class: 3, ex: '3x – 10 = 2x + 13', kq: 23 },
     { class: 3, ex: 'Rút gọn phân số 22/48', kq: 11 },
     { class: 3, ex: 'Rút gọn phân số 27/45', kq: 3 },
     { class: 3, ex: 'Rút gọn phân số 48/44', kq: 12 },
     { class: 3, ex: 'Rút gọn phân số 9/18', kq: 1 },
     { class: 3, ex: 'Rút gọn phân số 56/44', kq: 14 },
     { class: 3, ex: 'Rút gọn phân số 72/90', kq: 4 },
     { class: 3, ex: 'Rút gọn phân số 56/18', kq: 28 },
     { class: 3, ex: 'Rút gọn phân số 49/63', kq: 7 },
     { class: 3, ex: 'Rút gọn phân số 56/42', kq: 4 },
     { class: 3, ex: 'Rút gọn phân số 52/12', kq: 13 },
     { class: 3, ex: 'Rút gọn phân số 48/16', kq: 3 },
     { class: 3, ex: 'Rút gọn phân số 54/28', kq: 27 },
     { class: 3, ex: 'Rút gọn phân số 55/15', kq: 11 },
     { class: 3, ex: 'Rút gọn phân số 45/20', kq: 9 },
     { class: 3, ex: 'Rút gọn phân số 28/36', kq: 7 },
     { class: 3, ex: 'Rút gọn phân số 46/18', kq: 23 },
     { class: 3, ex: 'Rút gọn phân số 26/48', kq: 13 },
     { class: 3, ex: '104/4 = ?', kq: 26 },
     { class: 3, ex: '252/7 = ?', kq: 36 },
     { class: 3, ex: '225/25 = ?', kq: 9 },
     { class: 3, ex: '128/16 = ?', kq: 8 },
     { class: 3, ex: '774/6 = ?', kq: 129 },
     { class: 3, ex: '864/24 = ?', kq: 36 },
     { class: 3, ex: '936/13 = ?', kq: 72 },
     { class: 3, ex: '364/14 = ?', kq: 26 },
     { class: 3, ex: '644/28 = ?', kq: 23 },
     { class: 3, ex: '663/17 = ?', kq: 39 },
     { class: 3, ex: '400/16 = ?', kq: 25 },
     { class: 3, ex: '598/23 = ?', kq: 26 },
     { class: 3, ex: '522/29 = ?', kq: 18 },
     { class: 3, ex: '529/23 = ?', kq: 23 },
     { class: 3, ex: '532/28 = ?', kq: 19 },
     { class: 3, ex: '483/21 = ?', kq: 23 },
     { class: 3, ex: '616/56 = ?', kq: 11 },
     { class: 3, ex: '276/23 = ?', kq: 12 },
     { class: 3, ex: '726/22 = ?', kq: 33 },
     { class: 3, ex: '242/11 = ?', kq: 22 },
     { class: 3, ex: 'An và Huy có tất cả 26 hòn bi. Nếu An cho Huy 5 hòn bi, Huy cho An 7 hòn bi. Lúc này trong túi 2 bạn có bi = nhau. Hỏi lúc đầu An có bao nhiêu bi?', kq: 12 },
     { class: 3, ex: '806/31 = ?', kq: 26 },
     { class: 3, ex: 'Phép chia 278/12 có số dư là bao nhiêu ?', kq: 2 },
     { class: 3, ex: 'Phép chia 580/18 có số dư là bao nhiêu ?', kq: 4 },
     { class: 3, ex: 'Phép chia 299/13 có số dư là bao nhiêu ? ', kq: 0 },
     { class: 3, ex: 'Phép chia 99/9 có số dư là bao nhiêu', kq: 0 },
     { class: 3, ex: 'Phép chia 123/11 có số dư là bao nhiêu ?', kq: 2 },
     { class: 3, ex: 'Thực hiện phép nhân 234*12 = ? ', kq: 2808 },
     { class: 3, ex: 'Thực hiện phép nhân 354*21 = ? ', kq: 7434 },
     { class: 3, ex: 'Thực hiện phép nhân 128*18 = ? ', kq: 2304 },
     { class: 3, ex: 'Thực hiện phép nhân 212*19 = ? ', kq: 4028 },
     { class: 3, ex: 'Thực hiện phép nhân 456*9 = ? ', kq: 4104 },
     { class: 3, ex: 'Thực hiện phép nhân 243*22 = ? ', kq: 5346 },
     { class: 3, ex: 'Thực hiện phép nhân 178*18 = ? ', kq: 3204 },
     { class: 3, ex: 'Thực hiện phép nhân 245*26 = ? ', kq: 6370 },
     { class: 3, ex: 'Thực hiện phép nhân 234*16 = ? ', kq: 3744 },
     { class: 3, ex: 'Thực hiện phép nhân 432*15 = ? ', kq: 6480 },
     { class: 3, ex: 'Thực hiện phép nhân 453*29 = ? ', kq: 13137 },
     { class: 3, ex: 'Thực hiện phép nhân 567*26 = ? ', kq: 14742 },
     { class: 3, ex: 'Thực hiện phép nhân 124*19 = ? ', kq: 2356 },
     { class: 3, ex: 'Thực hiện phép nhân 224*22 = ? ', kq: 4928 },
     { class: 3, ex: 'Thực hiện phép tính sau : 14 - 4*7 + 28 - 19*2 + 8/2 = ?', kq: -20 },
     { class: 3, ex: 'Thực hiện phép tính sau : 23 + 12*7 + 67 - 19*6 + 36/4 = ?', kq: 72 },
     { class: 3, ex: 'Thực hiện phép tính sau : 90 - 12*7 + 35 - 43*2 + 81/9 = ?', kq: -36 },
     { class: 3, ex: 'Thực hiện phép tính sau : 67 + 22*7 - 46 + 9*13 - 45/9 = ?', kq: 287 },
     { class: 3, ex: 'Thực hiện phép tính sau : 56 - 18*5 + 42 - 37*2 + 64/8 = ?', kq: -58 },
     { class: 3, ex: 'Thực hiện phép tính sau : 34 + 19*5 - 30 + 26*4 + 63/7 = ?', kq: 212 },
     { class: 3, ex: 'Thực hiện phép tính sau : 18 - 27*4 = ?', kq: -90 },
     { class: 3, ex: 'Thực hiện phép tính sau : 27 - 39*14 = ?', kq: -519 },
     { class: 3, ex: 'Thực hiện phép tính sau : 45 + 34*12 = ?', kq: 453 },
     { class: 3, ex: 'Thực hiện phép tính sau : 38*2 + 12 - 39*14 = ?', kq: -458 },
     { class: 3, ex: 'Thực hiện phép tính sau : 27*5 - 18 - 39*14 = ?', kq: -429 },
     { class: 3, ex: 'Thực hiện phép tính sau : 72 - 29*4 - 19 = ?', kq: -63 },
     { class: 3, ex: 'Thực hiện phép tính sau : 67 + 8*19 - 39*14 = ?', kq: -327 },
     { class: 3, ex: 'Thực hiện phép tính sau : 34 + 81/9 - 39*14 = ?', kq: -503 },
     { class: 3, ex: 'Thực hiện phép nhân 333*13 = ? ', kq: 4329 },
     { class: 3, ex: 'Hai ngăn sách có tổng cộng 84 quyển. Nếu lấy 4 quyển sách của ngăn thứ nhất chuyển sang ngăn thứ hai thì số quyển sách của hai ngăn bằng nhau. Hỏi thực sự ngăn thứ nhất có bao nhiêu quyển sách?', kq: 46 },
     //Class Four
     // Class Five
     { class: 5, ex: 'Có hai hộp bi, hộp thứ nhất nếu bớt ra 4 viên bi thì sẽ có số bi kém hộp thứ hai 2 lần. Hỏi hộp thứ nhất ít hơn hộp thứ hai bao nhiêu viên bi? Biết hộp thứ hai có 28 viên bi?', kq: 10 },
     { class: 5, ex: ' Hồng có 28 quyển sách, số sách của Hồng so với số sách của Lan thì kém 3 lần. Hỏi Lan phải chuyển cho Hồng bao nhiêu quyển sách để số sách của Lan còn gấp 2 lần số sách của Hồng?', kq: 4 },
     { class: 5, ex: 'Có hai thùng dầu, thùng thứ nhất chứa 48 lít dầu, thùng thứ hai nếu có thêm 4 lít dầu thì số dầu ở thùng thứ hai so với thùng thứ nhất sẽ kém 2 lần. Hỏi phải cuyển từ thùng thứ nhất sang thùng thứ hai bao nhiêu lít dầu để hai thùng có số lít dầu bằng nhau?', kq: 14 },
     { class: 5, ex: 'Có hai bao đường, nếu lấy ở bao thứ nhất bớt 3kg thì bao thứ nhất còn nhiều hơn bao thứ hai 24kg và còn nhiều gấp 3 lần bao thứ hai. Hỏi hai bao đường có tất cả bao nhiêu ki-lô-gam?', kq: 51 },
     { class: 5, ex: 'Có hai tấm vải, một tấm màu xanh, một tấm màu đỏ, tấm vải xanh dài gấp 3 lần tấm vải đỏ. Cửa hàng đã bán hét 25m vải xanh và 7m vải đỏ thì số mét vải còn lại của hai tấm vải bằng nhau. Hỏi lúc chưa bán tấm vải đỏ dài bao nhiêu mét?', kq: 9 },
     { class: 5, ex: 'Có hai bao gạo, bao thứ nhất nặng 64kg. Biết rằng nếu bao thứ nhất có thêm 8kg gạo thì số gạo của bao thứ nhất so với bao thứ hai sẽ gấp 3 lần. Hỏi bao thứ nhất nhiều hơn bao thứ hai bao nhiêu ki-lô-gam gạo?', kq: 40 },
     { class: 5, ex: 'Dũng có một hộp 20 viên bi gồm 3 loại bi: bi xanh, bi đỏ và bi vàng. Biết số bi xanh gấp 6 lần số bi đỏ và gấp 2 lần số bi vàng. Hỏi bi đỏ có bao nhiêu viên bi?', kq: 2 },
     { class: 5, ex: '3(4 – x) – 2(x- 1) = x + 20', kq: -1 },
     { class: 5, ex: '3(x – 2) + 2x = 10', kq: 16 },
     { class: 5, ex: '3x - 7(2x - 1) - 4x = 8(3x -5) + 4', kq: 43 },
     { class: 5, ex: '4(2x + 7) – 3(3x – 2) = 24 ', kq: 10 },
     { class: 5, ex: '2(x-1) + 3(x-2) = x-4 ', kq: 1 },
     { class: 4, ex: '14 + 4x = 3x + 20', kq: 6 },
     { class: 5, ex: '3x + 16(3-2x) + 18 = 4 - 2x + 4( 3x+2 )', kq: 18 },
     { class: 4, ex: '5x-4(3x+2)-4x = 10-8(3-4x)', kq: 6 },
     { class: 5, ex: '4x+8-3(2x-4) = 10x+6', kq: 7 },
     { class: 5, ex: '3x-8+2(4x-5) = 7(2x-2)', kq: -4 },
     { class: 5, ex: 'x+8-2(3x-4)-5 = 3x+7', kq: 1 },
     { class: 5, ex: '4x-10+3(3x-5)-2 = 12+4x', kq: 13 },
     { class: 5, ex: '3x-4 = 4x-5+6(3x-2)', kq: 13 },
     { class: 5, ex: '4x+8 = 5x-3+6(3-2x)', kq: 7 },
     { class: 5, ex: '5x-9 = 3(x-6)+6(x-7)', kq: 51 },
     { class: 5, ex: 'Biết tổng 2 số bằng 49 và hiệu 2 số bằng 31, tìm số bé ?', kq: 9 },
     { class: 5, ex: 'Biết tổng 2 số bằng 36 và số lớn gấp 5 lần số bé, hỏi hiệu 2 số bằng bao nhiêu? ', kq: 24 },
     { class: 5, ex: 'Biết tổng 2 số bằng 42 và hiệu 2 số bằng 2, hỏi số lớn ?', kq: 22 },
     { class: 5, ex: 'Biết a + 3 = 2b và a - b = 6 tìm a + b ? ', kq: 24 },
     { class: 5, ex: 'Biết a - 3 = 4b và a - b = 18 tìm a + b', kq: 28 },
     { class: 5, ex: 'Biết a - 12 = 2b và a - b = 16 tìm a + b', kq: 24 },
     { class: 5, ex: 'Biết a - 3 = b và a + b = 33 tìm a - b', kq: 3 },
     { class: 5, ex: 'Biết a - 16 = b và a + b = 20 tìm a + 2b', kq: 22 },
     { class: 5, ex: 'Biết a - 9 = 2b và a - b = 11 tìm 2a - 3b', kq: 20 },
     { class: 5, ex: 'Biết a - b = 18 và a + b = 42 tìm a + 2b', kq: 54 },

];
var time = document.getElementById('time');
var start = document.getElementsByClassName('start')[0];
var slogan = document.getElementById('slogan');
var select = document.getElementById('select');
var namebt = document.getElementById('namebt');
var example = document.getElementById('example');
var result = document.getElementById('result');
var submit = document.getElementById('submit');
var err = document.getElementById('err');
var next = document.getElementById('next');
var sum = document.getElementById('sum');
var seach_class = document.getElementById('seach_class');

var scor = new Audio();
scor.src = "score.mp3";
var dea = new Audio();
dea.src = "dea.mp3";
next.style.display = 'none';

document.getElementsByClassName('container')[0].style.marginTop = '-150px';

//START LEANING
seach_class.addEventListener('click', () => {
     if (select.value == '0') {
          err.style.display = 'block';
          err.style.width = 'auto';
          err.innerHTML = `Chọn lớp!`;
     } else {
          var baitap = bai_tap_theo_lop.filter((x) => {
               return x.class === Number(select.value);
          });
          sum.innerHTML = `Tổng số bài tập Toán lớp ${select.value} đang có : ${baitap.length}`;
          if (baitap.length == 0) {
               slogan.innerHTML = `Bài tập Toán lớp ${select.value} hiện sắp được Update, vui lòng chờ thêm! Xin cảm ơn!`;
               start.style.display = 'none';
               err.style.display = 'none';
               slogan.style.marginTop = '120px';
               slogan.style.fontWeight = '500';
          } else {
               slogan.innerHTML = `Toán học lớp ${select.value}`;
               err.style.display = 'none';
               start.style.display = 'none';
               next.style.display = 'block';
               let times = () => {
                    let phut = 59;
                    let giay = 60;
                    setInterval(() => {
                         giay--;
                         if (giay == 0 && phut != 00) {
                              giay += 60;
                              --phut;
                         }
                         if (giay <= 9) giay = `0${giay}`;
                         time.innerHTML = `${phut}:${giay}`;
                         if (phut == 0 && giay == 0) {
                              time.innerHTML = 'Hết giờ !';
                         }


                    }, 1000);
               }
               times();
               var so_luong_bt = baitap.length;
               var n;
               var i = 0;
               let main = () => {
                    ++i;
                    console.log(`ket qua la : ${baitap[n].kq}`);
                    example.innerHTML = `Câu ${i}: ${baitap[n].ex}`;
                    next.style.display = 'none';
                    //dem nguoc
                    err.style.display = 'none';
                    //Gửi kết quả;
                    submit.addEventListener('click', () => {
                         let cau_tra_loi = Number(result.value);
                         if (result.value == '') {
                              err.style.display = 'block';
                              err.innerHTML = 'Hãy nhập kết quả !';
                              dea.play();
                         } else if (cau_tra_loi == baitap[n].kq) {
                              err.style.display = 'block';
                              err.innerHTML = 'Đúng rồi';
                              scor.play();
                              next.style.display = 'block';

                         }
                         else if (cau_tra_loi != baitap[n].kq) {
                              err.style.display = 'block';
                              err.innerHTML = 'Xem lại kết quả';
                              dea.play();
                         }
                    });
                    result.addEventListener('click', () => {
                         err.style.display = 'none';
                    });

               }



               //Chuyen bai;
               next.addEventListener('click', () => {
                    slogan.style.display = 'none';
                    next.style.width = '50%';
                    document.getElementsByClassName('container')[0].style.marginTop = '0px';
                    namebt.style.display = 'block';
                    example.style.display = 'block';
                    result.style.display = 'block';
                    submit.style.display = 'block';
                    err.style.display = 'block';
                    next.innerHTML = 'Chuyển bài';

                    n = Math.floor(Math.random() * so_luong_bt);
                    result.value = '';
                    main();
               });
          }
     }
})
